import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { chromium } from "playwright-core";
import { generateAssistantReply, providerInput } from "../../src/lib/assistant/assistantProvider.ts";
import { DiamondAssistantJobService } from "../../src/lib/assistant/assistantJobService.ts";
import { ASSISTANT_MODEL, type Session } from "../../src/lib/assistant/assistantContracts.ts";

const cwd=process.cwd(), root=resolve("output/spec-0012/phase-2-final-correction/repeated-browser");mkdirSync(root,{recursive:true});
const sandbox=resolve(root,"sandbox");const directory=resolve(sandbox,"output/diamond-assistant-private");mkdirSync(resolve(directory,"budget.lock"),{recursive:true});const ledger=resolve(directory,"budget.json");writeFileSync(ledger,JSON.stringify({schema:"diamond-assistant-budget/v1",days:{"2026-09-22":1000},months:{"2026-09":1000}}));const before=readFileSync(ledger);process.chdir(sandbox);
process.env.OPENAI_API_KEY="deterministic-test-not-a-credential";let sdkCalls=0, posts=0, formerReservationsUsd=0;const errors:string[]=[],forbidden:string[]=[],assertions:string[]=[];
const equal=(a:unknown,b:unknown,name:string)=>{assert.deepEqual(a,b,name);assertions.push(name)};
globalThis.fetch=async(input,init)=>{sdkCalls++;assert.equal(String(input),"https://api.openai.com/v1/responses");const request=JSON.parse(String(init?.body));assert.equal(request.model,ASSISTANT_MODEL);assert.deepEqual(request.tools,[]);assert.equal(request.store,false);const response={id:`reply_${sdkCalls.toString().padStart(8,"0")}`,status:"completed",model:ASSISTANT_MODEL,usage:{input_tokens:200,output_tokens:150,total_tokens:350},output:[{type:"message",content:[{type:"output_text",text:JSON.stringify({answer:`This is explanation ${sdkCalls}. You can keep asking questions about Diamond Animator.`,title:"Learning Diamond Animator"})}]}]};return new Response(`event: response.completed\ndata: ${JSON.stringify({type:"response.completed",response})}\n\ndata: [DONE]\n\n`,{headers:{"content-type":"text/event-stream"}})};
const service=new DiamondAssistantJobService(async(request,options)=>{formerReservationsUsd+=(providerInput(request).estimatedTokens*2+4000*12)/1000000;return generateAssistantReply(request,options)});
const browser=await chromium.launch({executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",headless:true});
try{
 const context=await browser.newContext({viewport:{width:1440,height:814}});await context.route("**/*",async route=>{const request=route.request(),url=new URL(request.url());if(url.origin!=="http://127.0.0.1:57970"){forbidden.push(url.origin);await route.abort();return}if(url.pathname==="/api/diamond-assistant"){let snapshot;if(request.method()==="POST"){posts++;snapshot=service.submit(request.postDataJSON())}else if(request.method()==="DELETE")snapshot=service.cancelRequest(request.postDataJSON());else snapshot=service.get(url.searchParams.get("jobId")!,url.searchParams.get("sessionId")!);await route.fulfill({status:snapshot?200:404,contentType:"application/json",body:JSON.stringify(snapshot??{error:"unknown"})});return}if(url.pathname.startsWith("/api/")){forbidden.push(url.pathname);await route.abort();return}await route.continue()});
 const page=await context.newPage();page.on("pageerror",error=>errors.push(error.message));await page.goto("http://127.0.0.1:57970/assistant");await page.getByRole("button",{name:"New Chat",exact:true}).waitFor();
 for(let i=1;i<=12;i++){await page.getByLabel("Message the Assistant").fill(`Explain another Diamond Animator feature, question ${i}.`);await page.getByRole("button",{name:"Send",exact:true}).click();await page.getByRole("article",{name:"Assistant reply",exact:true}).filter({hasText:`This is explanation ${i}.`}).waitFor({timeout:15000});await page.getByRole("button",{name:"Send",exact:true}).waitFor();equal(await page.getByRole("article",{name:"Assistant reply",exact:true}).count(),i,`question ${i} completes in the same ordinary conversation`);equal((await page.locator("body").innerText()).includes("review budget"),false,`question ${i} never shows a cumulative budget failure`)}
 const sessions:Session[]=await page.evaluate(()=>new Promise((resolveRead,reject)=>{const open=indexedDB.open("diamond-assistant-session-v1");open.onsuccess=()=>{const db=open.result,tx=db.transaction("sessions"),get=tx.objectStore("sessions").getAll();tx.oncomplete=()=>{db.close();resolveRead(get.result)};tx.onerror=()=>reject(tx.error)}}));
 equal(sessions.length,1,"repeated questions stay in one persisted chat");equal(sessions[0].messages.length,24,"all twelve user/answer pairs persist");equal(sessions[0].turns.every(t=>t.status==="done"&&t.usage?.model===ASSISTANT_MODEL&&t.usage?.estimatedCostUsd===.0022),true,"all terminal receipts retain usage/model/cost reporting");equal(posts,12,"exactly twelve explicit UI Sends");equal(sdkCalls,12,"exactly one actual SDK transport-double invocation per Send");assert.ok(formerReservationsUsd>.6);assertions.push("same conversation exceeds the former daily reservation cap without a stop");equal(readFileSync(ledger),before,"pre-existing exhausted ledger bytes remain unchanged despite old lock directory");equal(errors,[],"zero browser page errors");equal(forbidden,[],"zero external or unrelated browser requests");
 await page.getByRole("article",{name:"Assistant reply",exact:true}).last().locator('[data-assistant-reveal="complete"]').waitFor();
 await page.screenshot({path:resolve(root,"twelve-answers.png")});writeFileSync(resolve(root,"result.json"),JSON.stringify({status:"PASS",assertions,posts,sdkTransportDoubleCalls:sdkCalls,formerReservationsUsd,errors,forbidden,legacyLedgerSha256:createHash("sha256").update(before).digest("hex"),legacyLedgerUnchanged:true,realProviderCalls:0,paidCalls:0,automatedCostUsd:0},null,2));console.log(JSON.stringify({status:"PASS",assertions:assertions.length,posts,sdkTransportDoubleCalls:sdkCalls}));
}finally{await browser.close();process.chdir(cwd)}
