import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
const root="output/spec-0012/phase-2-final-correction", priorRoot="output/spec-0012/phase-2-correction", originalRoot="output/spec-0012/phase-2";
const base="652431396e78370f3dfb7549294e66d154c3b7d4", priorHash="68953d8900f793676cdb5eaa611a449112664b4f1af504690cac9a682cd5e6f5", originalHash="63a87f3e832a200a52c18115fa9ed7533eaf1fb4b5cfc01438e2c1f8c1b3c8ec";
const json=(path:string)=>JSON.parse(readFileSync(path,"utf8"));const sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");const bind=(path:string)=>{const bytes=readFileSync(path);return{path,bytes:bytes.length,sha256:sha(bytes)}};type Binding=ReturnType<typeof bind>;
const git=(...args:string[])=>execFileSync("git",args,{encoding:"utf8"}).trim();
const prior=json(`${priorRoot}/proof-manifest.json`),original=json(`${originalRoot}/proof-manifest.json`),baseline=json(`${root}/baseline-bindings.json`);
assert.equal(bind(`${priorRoot}/proof-manifest.json`).sha256,priorHash);assert.equal(bind(`${originalRoot}/proof-manifest.json`).sha256,originalHash);
for(const item of [...prior.evidence,...original.evidence,original.spec] as Binding[])assert.deepEqual(bind(item.path),item);
for(const item of [...baseline.sources,...prior.original.sourceSnapshots]){const bytes=readFileSync(item.backupPath);assert.equal(bytes.length,item.bytes);assert.equal(sha(bytes),item.sha256)}
const changed=["scripts/spec0012-assistant/phase2Oracle.ts","src/lib/assistant/assistantJobService.ts","src/lib/assistant/assistantProvider.ts"].sort();
const added=["phase2FinalCorrectionOracle","phase2FinalCorrectionBrowser","runPhase2FinalCorrectionProof","recordPhase2FinalCorrectionProof","validatePhase2FinalCorrectionProof"].map(name=>`scripts/spec0012-assistant/${name}.ts`).sort();
const paths=[...prior.dirtyPathAllowlist,...added].sort();const dirty=[...new Set([...git("ls-files","-m").split("\n"),...git("ls-files","--others","--exclude-standard").split("\n")].filter(Boolean))].sort();
assert.equal(git("rev-parse","HEAD"),base);assert.equal(git("branch","--show-current"),"");assert.equal(git("diff","--cached","--name-only"),"");assert.deepEqual(dirty,paths);
assert.deepEqual(prior.sources.filter((item:Binding)=>sha(readFileSync(item.path))!==item.sha256).map((item:Binding)=>item.path).sort(),changed);
mkdirSync(`${root}/receipts`,{recursive:true});
if(!process.argv.includes("--seal")){
 for(const[id,command,args]of[["typescript",process.execPath,["node_modules/typescript/bin/tsc","--noEmit","--incremental","false"]],["focused-lint",process.execPath,["node_modules/eslint/bin/eslint.js",...paths.filter(p=>/\.tsx?$/.test(p))]],["diff-check","git",["diff","--check"]]]as Array<[string,string,string[]]>){const result=spawnSync(command,args,{encoding:"utf8",maxBuffer:64*1024*1024});writeFileSync(`${root}/receipts/${id}.json`,JSON.stringify({id,command:[command,...args],exitCode:result.status,stdout:result.stdout,stderr:result.stderr},null,2));assert.equal(result.status,0,result.stdout+result.stderr)}
 const lint=spawnSync(process.execPath,["node_modules/eslint/bin/eslint.js",".","--ignore-pattern","output/**","--format","json","--output-file",`${root}/lint-final.json`],{encoding:"utf8",maxBuffer:64*1024*1024});assert.equal(lint.status,1);const findings=(json(`${root}/lint-final.json`) as Array<{filePath:string;errorCount:number;warningCount:number}>).filter(x=>x.errorCount||x.warningCount);
 for(const item of findings){const path=item.filePath.replace(`${process.cwd()}/`,"");assert.deepEqual(readFileSync(path),execFileSync("git",["show",`${base}:${path}`]))}const errors=findings.reduce((s,x)=>s+x.errorCount,0),warnings=findings.reduce((s,x)=>s+x.warningCount,0);assert.equal(errors,5);assert.equal(warnings,81);writeFileSync(`${root}/receipts/lint-nonregression.json`,JSON.stringify({status:"PASS",errors,warnings,newFindings:[],verifiedUnchangedFiles:findings.map(x=>bind(x.filePath.replace(`${process.cwd()}/`,"")))},null,2));
 writeFileSync(`${root}/receipts/preservation.json`,JSON.stringify({status:"PASS",originalManifestSha256:originalHash,priorManifestSha256:priorHash,originalEvidenceBindings:67,priorEvidenceBindings:101,originalSourceSnapshots:25,priorSourceSnapshots:29,changedExisting:changed,added,unchangedPriorPaths:prior.sources.filter((item:Binding)=>!changed.includes(item.path)).map((item:Binding)=>item.path),indexEmpty:true},null,2));console.log("PASS final TypeScript/lint/diff, exact boundary and both sealed proof preservation checks");
}else{
 const resultPaths=["oracle.json","correction-oracle.json","final-correction-oracle.json","browser/result.json","presentation/result.json","repeated-browser/result.json","protected-browser/result.json","restart/result.json","faults/result.json","animator-smoke/result.json","regressions/result.json","build/result.json","production-verification.json","production-smoke.json"];
 for(const path of resultPaths)assert.equal(json(`${root}/${path}`).status,"PASS");for(const id of ["typescript","focused-lint","diff-check"])assert.equal(json(`${root}/receipts/${id}.json`).exitCode,0);
 const collect=(path:string):string[]=>readdirSync(path,{withFileTypes:true}).flatMap(entry=>entry.name==="baseline-sources"||entry.name.startsWith("profile-")?[]:entry.isDirectory()?collect(`${path}/${entry.name}`):[`${path}/${entry.name}`]);
 const evidencePaths=[...collect(root).filter(path=>! /\/(proof-manifest\.json|validation-receipt\.json|independent-validation[^/]*|Implementation-Review-Packet\.md|review-server\.log)$/.test(path)),...["full","focused"].map(kind=>`output/spec-0012/phase-1-correction/environment/phase2-final-correction-build-${kind}-network.jsonl`)].sort();
 const sources=paths.map(bind);const oracle=json(`${root}/final-correction-oracle.json`),browser=json(`${root}/repeated-browser/result.json`);
 const manifest={schema:"spec0012-phase2-final-correction-proof/v1",status:"PASS_WITH_RECORDED_LIMITATIONS",generatedAt:new Date().toISOString(),base,head:git("rev-parse","HEAD"),branch:"",worktree:process.cwd(),indexEmpty:true,dirtyPathAllowlist:paths,actualDirtyPaths:dirty,sources,sourceDigest:sha(JSON.stringify(sources)),evidence:evidencePaths.map(bind),
  preservation:{originalManifest:bind(`${originalRoot}/proof-manifest.json`),priorManifest:bind(`${priorRoot}/proof-manifest.json`),baseline:bind(`${root}/baseline-bindings.json`),priorSourceSnapshots:baseline.sources,originalEvidenceBindings:67,priorEvidenceBindings:101},
  changedExisting:changed,added,authority:{sourceTask:"01a0b45e-dd0b-73c3-b42d-d5b49dced309",phase:2,scope:"Arthur explicitly authorizes complete removal of cumulative local Assistant daily/monthly reservation/caps and file/lock failure paths; all other boundaries retained",modeLimitation:"Default mode with no switch tool; read-only boot/tracing before editing; no claim Plan mode was active",ownership:"Same sole Spec Executor; existing read-only reviewer only; no new executor or CPA transfer",canonicalConflict:"Latest explicit authority supersedes cumulative review-budget decisions; canonical docs remain untouched for later CPA"},
  limits:prior.limits,costPolicy:{model:"gpt-5.6-terra",reasoning:["low","medium","high","xhigh"],defaultReasoning:"medium",requestUsd:.15,inputTokens:24000,outputTokens:4000,deadlineMs:90000,maxRetries:0,activeJobs:2,sessions:50,jobMemory:500,dailyCap:null,monthlyCap:null,ledgerGate:false,tools:[],store:false,localOnly:true,automaticResends:false,usageReporting:true},
  proof:{successfulRepeatedProviderCalls:oracle.successfulRepeatedProviderCalls,sdkOracleTransportDoubles:oracle.sdkTransportDoubleCalls,repeatedUiQuestions:browser.posts,sdkUiTransportDoubles:browser.sdkTransportDoubleCalls,formerReservationTotalUsd:oracle.formerReservationsUsd,simulatedUsageTotalUsd:oracle.simulatedUsageUsd,oldBudgetRuntimePathsAbsent:true,legacyLedgerInert:true,realProviderCalls:0,paidCalls:0,automatedCostUsd:0},
  review:{url:"http://127.0.0.1:57970/assistant",port:57970,production:true,existingCredentialPreserved:true,automatedProviderCallsAfterEnablement:0},humanAcceptance:"pending Arthur and Project Manager",controlPlaneUpdated:false,gitPublication:false,staged:false,committed:false,pushed:false,deployed:false,laterPhaseStarted:false,
  ownership:"Sole Spec Executor stops after final packet; no CPA ownership transfer",cleanupPlan:"Retain exact review server/worktree and both prior seals until acceptance, sequential CPA and separate authorized publication/synchronization; D-0054 cleanup is later",
  limitations:["Live provider access/answer quality unproven: executor automated calls are zero; no claim about Arthur manual usage","Full build retains unchanged app/dev/ai-costs/lifetime/page.tsx PageProps/searchParams failure; focused production build passes","Full lint retains inherited 5 errors and 81 warnings in unchanged base files; focused lint passes","Historical Animator transient reveal observation remains unproven; focused Animator smoke and protected byte equality pass","Chromium/emulated profiles only; no physical-device or non-Chromium claim","Canonical control plane untouched; acceptance, CPA propagation and publication remain separate","Cumulative local spending cap intentionally absent under Arthur authority; preserved request/job/token boundaries remain"]};
 writeFileSync(`${root}/proof-manifest.json`,JSON.stringify(manifest,null,2)+"\n",{flag:"wx"});console.log(JSON.stringify({status:"SEALED",manifest:bind(`${root}/proof-manifest.json`),sourceDigest:manifest.sourceDigest,sourceFiles:paths.length,evidenceFiles:evidencePaths.length}));
}
