import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";

const root = "output/spec-0012/phase-4"; const base = "fa2ef6c526d04de9c77b356b53b4768890c46e1f"; const branch = "codex/spec0012-phase-4-fresh-search";
const specPath = "docs/specs/0012-diamond-animator-guidance-assistant.md";
const changed = [
  "src/components/assistant/AssistantComposer.tsx", "src/components/assistant/AssistantConversation.tsx", "src/components/assistant/AssistantText.tsx", "src/components/assistant/diamondAssistant.module.css",
  "src/components/assistant/useAssistantSessions.ts", "src/lib/assistant/assistantContracts.ts", "src/lib/assistant/assistantJobService.ts", "src/lib/assistant/assistantKnowledge.ts", "src/lib/assistant/assistantProvider.ts", "src/lib/assistant/assistantStorage.ts",
].sort();
const added = [
  "scripts/spec0012-assistant/phase4BrowserProof.ts", "scripts/spec0012-assistant/phase4BrowserRegressions.ts", "scripts/spec0012-assistant/phase4BuildProof.ts", "scripts/spec0012-assistant/phase4CorruptRowProof.ts", "scripts/spec0012-assistant/phase4FaultProof.ts", "scripts/spec0012-assistant/phase4FinalLiveSearch.ts", "scripts/spec0012-assistant/phase4Fixtures.ts", "scripts/spec0012-assistant/phase4LiveDiagnostic.ts", "scripts/spec0012-assistant/phase4LivePostmortem.ts", "scripts/spec0012-assistant/phase4LiveProof.ts", "scripts/spec0012-assistant/phase4LiveSearchOnly.ts", "scripts/spec0012-assistant/phase4OfficialEvidence.ts", "scripts/spec0012-assistant/phase4Oracle.ts", "scripts/spec0012-assistant/phase4Regressions.ts", "scripts/spec0012-assistant/recordPhase4Proof.ts", "scripts/spec0012-assistant/validatePhase4Proof.ts", "src/lib/assistant/assistantSearchPolicy.ts",
].sort();
const paths = [...changed, ...added].sort(); const git = (...args: string[]) => execFileSync("git", args, { encoding: "utf8" }).trim();
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex"); const bind = (path: string) => { const bytes = readFileSync(path); return { path, bytes: bytes.length, sha256: sha(bytes) }; };
const json = (path: string) => JSON.parse(readFileSync(path, "utf8"));
const dirty = [...new Set([...git("ls-files", "-m").split("\n"), ...git("ls-files", "--others", "--exclude-standard").split("\n")].filter(Boolean))].sort();
assert.equal(git("rev-parse", "HEAD"), base); assert.equal(git("branch", "--show-current"), branch); assert.equal(git("diff", "--cached", "--name-only"), ""); assert.deepEqual(dirty, paths);

mkdirSync(`${root}/receipts`, { recursive: true });
for (const [id, command, args] of [
  ["typescript", process.execPath, ["node_modules/typescript/bin/tsc", "--noEmit", "--incremental", "false"]],
  ["focused-lint", process.execPath, ["node_modules/eslint/bin/eslint.js", ...paths.filter(path => /\.tsx?$/.test(path))]],
  ["diff-check", "git", ["diff", "--check"]],
] as Array<[string, string, string[]]>) {
  const result = spawnSync(command, args, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 }); writeFileSync(`${root}/receipts/${id}.json`, JSON.stringify({ id, command: [command, ...args], exitCode: result.status, stdout: result.stdout, stderr: result.stderr }, null, 2)); assert.equal(result.status, 0, result.stdout + result.stderr);
}
const health = spawnSync("curl", ["-s", "-o", "/dev/null", "-w", "%{http_code}", "http://127.0.0.1:58040/assistant"], { encoding: "utf8" }); assert.equal(health.status, 0); assert.equal(health.stdout, "200");
const listener = execFileSync("lsof", ["-nP", "-iTCP:58040", "-sTCP:LISTEN", "-t"], { encoding: "utf8" }).trim(); assert.match(listener, /^\d+$/);
writeFileSync(`${root}/review-server.json`, JSON.stringify({ status: "PASS", url: "http://127.0.0.1:58040/assistant", port: 58040, pid: Number(listener), mode: "production", healthStatus: 200, cwd: process.cwd(), credentialFileIgnored: git("check-ignore", ".env.local") === ".env.local", credentialFileTracked: git("ls-files", ".env.local") !== "", credentialContentsDisplayed: false, sha256EqualityVerified: true, environmentRepair: "Canonical ignored .env.local copied byte-for-byte without displaying contents; equality verified before restart", liveConfigurationResult: "Configured greeting completed locally; after the bounded source-normalization correction, the final authorized exact search completed with visible search activity, persisted citations and an unchanged project sentinel" }, null, 2));

for (const path of ["oracle/result.json", "browser/result.json", "build/result.json", "corrupt-row/result.json", "faults/run/result.json", "regressions/result.json", "regression-browsers/result.json", "official-evidence.json"]) assert.equal(json(`${root}/${path}`).status, "PASS", path);
const configuredFailure = json(`${root}/live/failure.json`); assert.equal(configuredFailure.liveCallsStarted, 2); assert.equal(configuredFailure.retries, 0); const preconfigurationSearch = json(`${root}/live/search-result.json`); assert.equal(preconfigurationSearch.status, "LIVE_ACCESS_FAILED"); assert.equal(preconfigurationSearch.cumulativeLiveCalls, 2); assert.equal(preconfigurationSearch.retries, 0); assert.equal(preconfigurationSearch.answerPublished, false); assert.match(preconfigurationSearch.safeError, /not configured/); const livePostmortem = json(`${root}/live/postmortem.json`); assert.equal(livePostmortem.status, "PASS_WITH_RECORDED_LIMITATION"); assert.equal(livePostmortem.configuredVerification.searchingTextObserved, true); assert.equal(livePostmortem.configuredVerification.searchTerminalAnswerObserved, false); const diagnostic = json(`${root}/live/diagnostic.json`); assert.equal(diagnostic.status, "DIAGNOSTIC_TERMINAL_FAILURE"); assert.equal(diagnostic.requestCount, 1); assert.equal(diagnostic.retries, 0); assert.match(diagnostic.terminalError, /source limit was exceeded/); const finalSearch = json(`${root}/live/final-search-result.json`); assert.equal(finalSearch.status, "PASS"); assert.equal(finalSearch.requestCount, 1); assert.equal(finalSearch.retries, 0); assert.equal(finalSearch.terminalStatus, "done"); assert.equal(finalSearch.searchingTextObserved, true); assert.equal(finalSearch.finalizingObserved, true); assert.equal(finalSearch.citationsPersistedAcrossReload, true); assert.equal(finalSearch.projectSentinelUnchanged, true); assert.ok(finalSearch.estimatedCostUsd <= .15);
const collect = (path: string): string[] => readdirSync(path, { withFileTypes: true }).flatMap(entry => entry.name.startsWith("profile-") ? [] : entry.isDirectory() ? collect(`${path}/${entry.name}`) : /^(proof-manifest\.json|validation-receipt\.json)$/.test(entry.name) ? [] : [`${path}/${entry.name}`]);
const previousManifest = bind(`${root}/pre-storage-correction-proof-manifest.json`); const previousValidation = bind(`${root}/pre-storage-correction-validation-receipt.json`);
assert.deepEqual(previousManifest, { path: `${root}/pre-storage-correction-proof-manifest.json`, bytes: 36978, sha256: "f29b22dbc6f112a4ca939bfaf908e5102710dfc6bac194954efb254c3a22a18a" });
assert.equal(previousValidation.sha256, "ec8f0f37158a9e672b4a5fe3b8c138016efe7078221a637c6adc39a6dcc1f96b");
const previous = json(previousManifest.path); assert.equal(previous.sourceDigest, "7dd51abe690337cd83535a6e41ec860f1fce1ffcdd0c58d095936b60f588c1d1");
const priorSource = new Map<string, { path: string; bytes: number; sha256: string }>(previous.sources.map((binding: { path: string; bytes: number; sha256: string }) => [binding.path, binding]));
const unchangedSearchProviderPaths = ["src/components/assistant/AssistantComposer.tsx", "src/components/assistant/AssistantConversation.tsx", "src/components/assistant/AssistantText.tsx", "src/components/assistant/diamondAssistant.module.css", "src/lib/assistant/assistantContracts.ts", "src/lib/assistant/assistantJobService.ts", "src/lib/assistant/assistantKnowledge.ts", "src/lib/assistant/assistantProvider.ts", "src/lib/assistant/assistantSearchPolicy.ts"];
const unchangedSearchProviderSources = unchangedSearchProviderPaths.map(path => { const current = bind(path); assert.deepEqual(current, priorSource.get(path), path); return current; });
const acceptedRuntimeFreeze = [bind("src/lib/assistant/assistantStorage.ts"), bind("src/components/assistant/useAssistantSessions.ts")];
assert.deepEqual(acceptedRuntimeFreeze.map(binding => binding.sha256), ["c0c91ef607025f707d40b5af5e644aad12f0ef824a76e87f9e1279ee362cf80c", "1b3ae967b385ca2b5114b1883cb940c2af62ccc8fcfa7518b895d725c2bd2ac9"]);
const corruptRow = json(`${root}/corrupt-row/result.json`); assert.equal(corruptRow.assertionCount, 27); assert.equal(corruptRow.corruptRow.sha256Before, corruptRow.corruptRow.sha256After); assert.equal(corruptRow.corruptRow.exactCanonicalEquality, true); assert.equal(corruptRow.healthyRow.finalReasoning, "high"); assert.equal(corruptRow.capacity.rawRowCount.mutationRejected, true); assert.equal(corruptRow.capacity.rawBytes.mutationRejected, true); assert.equal(corruptRow.requestLedger.realProviderCalls, 0); assert.equal(corruptRow.requestLedger.paidCalls, 0); assert.equal(corruptRow.requestLedger.liveSearchCalls, 0);
const sources = paths.map(bind); const evidence = collect(root).sort().map(bind); const protectedFamilies = json(`${root}/regressions/result.json`).protectedFamilies;
const manifest = {
  schema: "spec0012-phase4-proof/v1", status: "PASS_WITH_RECORDED_LIMITATIONS", generatedAt: new Date().toISOString(), base, head: git("rev-parse", "HEAD"), branch, worktree: process.cwd(), indexEmpty: true,
  dirtyPathAllowlist: paths, actualDirtyPaths: dirty, changedExisting: changed, added, spec: bind(specPath), sources, sourceDigest: sha(JSON.stringify(sources)), evidence,
  authority: { phase: 4, scope: "Automatic hosted internet search only when genuinely needed; preserve all Phase 2 Assistant behavior and every protected system", liveCeiling: "Initial configured verification: one local greeting and one exact implicit search; later explicit authority: one minimal diagnostic request and, after the narrow correction, one final exact UI search; no request was retried; this accepted-storage proof correction made zero live provider or search calls", correction: "Arthur and the Project Manager accepted the final Phase 4 review copy and authorized only technical-proof completion before later sequential CPA propagation/publication", ownership: "Sole correction Spec Executor in the active /353d/ worktree; no Control Plane Architect transfer", canonicalControlPlane: "Read-only; no AGENTS.md, docs, or project tree changes" },
  limits: { model: "gpt-5.6-terra", reasoning: ["low", "medium", "high", "xhigh"], defaultReasoning: "medium", sessions: 50, messages: 200, sessionBytes: 1048576, databaseBytes: 33554432, contextMessages: 32, contextChars: 48000, inputTokens: 24000, outputTokens: 4000, jobDeadlineMs: 90000, searchDeadlineMs: 45000, activeJobs: 2, requestUsd: .15, webSearchCallUsd: .01, webSearchToolCalls: 2, processedSources: 8, displayedSources: 6, queryChars: 512, maxRetries: 0, store: false, localTools: [], searchTools: ["web_search"], arbitraryFetch: false, mediaInspection: false, projectMutation: false },
  proof: { deterministicOracleAssertions: json(`${root}/oracle/result.json`).assertions.length, phase4BrowserAssertions: json(`${root}/browser/result.json`).assertions.length, corruptRowBrowserAssertions: corruptRow.assertionCount, faultAssertions: json(`${root}/faults/run/result.json`).assertions.length, inheritedAssistantBrowserAssertions: json(`${root}/regression-browsers/browser/result.json`).assertions.length, presentationAssertions: json(`${root}/regression-browsers/presentation/result.json`).assertions.length, protectedBrowserAssertions: json(`${root}/regression-browsers/protected-browser/result.json`).assertions.length, restartAssertions: json(`${root}/regression-browsers/restart/result.json`).assertions.length, repeatedBrowserAssertions: json(`${root}/regression-browsers/final-correction/repeated-browser/result.json`).assertions.length, animatorSmokeAssertions: json(`${root}/regression-browsers/animator-smoke/result.json`).assertions, protectedOracleCount: json(`${root}/regressions/protected-oracles/result.json`).receipts.length, protectedDiff: json(`${root}/regressions/result.json`).protectedDiff, typecheck: "PASS", focusedLint: "PASS", diffCheck: "PASS", fullBuild: json(`${root}/build/result.json`).full.status, focusedBuild: json(`${root}/build/result.json`).focused.status, deterministicProviderCalls: corruptRow.requestLedger.deterministicProviderCalls, deterministicPaidCalls: 0, correctionRealProviderCalls: corruptRow.requestLedger.realProviderCalls, correctionLiveSearchCalls: corruptRow.requestLedger.liveSearchCalls },
  proofCorrection: { previousSeal: { manifest: previousManifest, validation: previousValidation, sourceDigest: previous.sourceDigest }, acceptedRuntimeFreeze: { verifiedExact: true, sources: acceptedRuntimeFreeze }, unchangedSearchProviderFreeze: { verifiedExactAgainstPreviousSeal: true, sources: unchangedSearchProviderSources }, corruptRow: { result: bind(`${root}/corrupt-row/result.json`), assertionCount: corruptRow.assertionCount, preservedCanonicalSha256: corruptRow.corruptRow.sha256After, exactCanonicalEquality: corruptRow.corruptRow.exactCanonicalEquality, healthyChatCreated: true, finalReasoning: corruptRow.healthyRow.finalReasoning, corruptKeyOverwriteRejected: true, rawRowCountCapacityProven: corruptRow.capacity.rawRowCount.mutationRejected, rawByteCapacityProven: corruptRow.capacity.rawBytes.mutationRejected, uiUsable: true, realProviderCalls: 0, paidCalls: 0, liveSearchCalls: 0 } },
  live: { preconfigurationAttempts: { uiSends: 2, retries: 0, providerConfigured: false, successfulAnswers: 0, exactSearchError: preconfigurationSearch.safeError, countedAgainstConfiguredLiveCeiling: false }, initialConfiguredAuthorization: { authorizedSends: 2, actualSends: 2, retries: 0, result: "Greeting passed; exact search exposed the source-cap defect before publication" }, diagnosticAuthorization: { authorizedRequests: 1, actualRequests: diagnostic.requestCount, retries: diagnostic.retries, terminalError: diagnostic.terminalError }, finalAuthorization: { authorizedUiSends: 1, actualUiSends: finalSearch.requestCount, retries: finalSearch.retries }, totalUiSends: 5, totalDiagnosticApiRequests: 1, successfulAnswers: 2, greeting: { request: "Hi, who are you?", visibleReply: true, modelAndZeroToolAssertionsPassed: true, receiptAssertionsPassedBeforeSearch: true }, search: { request: finalSearch.prompt, terminalStatus: finalSearch.terminalStatus, elapsedMs: finalSearch.elapsedMs, model: finalSearch.model, reasoning: finalSearch.reasoning, toolCalls: finalSearch.toolCalls, processedSourceCount: finalSearch.processedSourceCount, displayedSources: finalSearch.displayedSources, searchingTextObserved: finalSearch.searchingTextObserved, searchingScreenshot: "output/spec-0012/phase-4/live/final-searching.png", finalizingObserved: finalSearch.finalizingObserved, answerPublished: true, citationsPublished: true, citationsPersistedAcrossReload: finalSearch.citationsPersistedAcrossReload, answerScreenshot: "output/spec-0012/phase-4/live/final-cited-answer.png", projectSentinelUnchanged: finalSearch.projectSentinelUnchanged, errors: finalSearch.errors, externalBrowserRequests: finalSearch.external }, billedUsageReceipt: { finalSuccessfulRequestEstimatedCostUsd: finalSearch.estimatedCostUsd, finalSuccessfulRequestCeilingUsd: .15, priorFailedSearchToolCostReported: false }, limitation: "The final successful request has an exact application receipt; the provider cost of the two earlier authorized search requests that reached the tool but failed before an application receipt is not reported" },
  officialEvidence: { sourceCount: json(`${root}/official-evidence.json`).sources.length, result: bind(`${root}/official-evidence.json`) },
  protected: { families: protectedFamilies, diffFromActivationBase: [], projectSentinelsUnchanged: true, externalBrowserRequests: 0, unrelatedApiRequests: 0 },
  review: { url: "http://127.0.0.1:58040/assistant", port: 58040, production: true, healthStatus: 200, liveProviderConfigured: true },
  humanAcceptance: "accepted by Arthur and Project Manager before this technical-proof correction", controlPlaneUpdated: false, gitPublication: false, staged: false, committed: false, pushed: false, deployed: false, laterPhaseStarted: false,
  ownership: "Sole correction Spec Executor stops after this packet; no CPA ownership transfer has occurred", cleanupPlan: "Retain this exact review server/worktree and proof through sequential CPA propagation, separate publication/synchronization, then D-0054 cleanup",
  limitations: ["The full repository build still has the byte-identical inherited app/dev/ai-costs/lifetime/page.tsx PageProps/searchParams baseline failure; the focused production build for all affected routes passes", "The final successful search has an exact $0.050754 application cost receipt; the provider cost of the two earlier authorized search requests that reached hosted search but failed before application receipts is unknown", "Two preconfiguration UI sends failed before usable provider access; they never reached the provider and were superseded after Arthur authorized the exact ignored-environment repair", "Corrupt-row UI and storage behavior is proven in Chromium BrowserContexts with isolated IndexedDB databases; no physical-device or non-Chromium claim", "Canonical control-plane propagation, publication, deployment, and later phases remain untouched"],
};
assert.deepEqual(git("diff", "--name-only", base, "--", ...protectedFamilies).split("\n").filter(Boolean), []);
writeFileSync(`${root}/proof-manifest.json`, `${JSON.stringify(manifest, null, 2)}\n`, { flag: "wx" });
console.log(JSON.stringify({ status: "SEALED", manifest: bind(`${root}/proof-manifest.json`), sourceDigest: manifest.sourceDigest, sources: sources.length, evidence: evidence.length }));
