import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const root = "output/spec-0012/phase-4"; const base = "fa2ef6c526d04de9c77b356b53b4768890c46e1f"; const branch = "codex/spec0012-phase-4-fresh-search";
const changed = [
  "src/components/assistant/AssistantComposer.tsx", "src/components/assistant/AssistantConversation.tsx", "src/components/assistant/AssistantText.tsx", "src/components/assistant/diamondAssistant.module.css",
  "src/components/assistant/useAssistantSessions.ts", "src/lib/assistant/assistantContracts.ts", "src/lib/assistant/assistantJobService.ts", "src/lib/assistant/assistantKnowledge.ts", "src/lib/assistant/assistantProvider.ts", "src/lib/assistant/assistantStorage.ts",
].sort();
const added = [
  "scripts/spec0012-assistant/phase4BrowserProof.ts", "scripts/spec0012-assistant/phase4BrowserRegressions.ts", "scripts/spec0012-assistant/phase4BuildProof.ts", "scripts/spec0012-assistant/phase4CorruptRowProof.ts", "scripts/spec0012-assistant/phase4FaultProof.ts", "scripts/spec0012-assistant/phase4FinalLiveSearch.ts", "scripts/spec0012-assistant/phase4Fixtures.ts", "scripts/spec0012-assistant/phase4LiveDiagnostic.ts", "scripts/spec0012-assistant/phase4LivePostmortem.ts", "scripts/spec0012-assistant/phase4LiveProof.ts", "scripts/spec0012-assistant/phase4LiveSearchOnly.ts", "scripts/spec0012-assistant/phase4OfficialEvidence.ts", "scripts/spec0012-assistant/phase4Oracle.ts", "scripts/spec0012-assistant/phase4Regressions.ts", "scripts/spec0012-assistant/recordPhase4Proof.ts", "scripts/spec0012-assistant/validatePhase4Proof.ts", "src/lib/assistant/assistantSearchPolicy.ts",
].sort();
const expected = [...changed, ...added].sort(); const git = (...args: string[]) => execFileSync("git", args, { encoding: "utf8" }).trim(); const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex"); const json = (path: string) => JSON.parse(readFileSync(path, "utf8"));
type Binding = { path: string; bytes: number; sha256: string }; const verify = (binding: Binding) => { assert.ok(!binding.path.startsWith("/") && !binding.path.includes("..") && !binding.path.includes(".env")); const bytes = readFileSync(binding.path); assert.equal(bytes.length, binding.bytes); assert.equal(sha(bytes), binding.sha256, binding.path); };
const collect = (path: string): string[] => readdirSync(path, { withFileTypes: true }).flatMap(entry => entry.name.startsWith("profile-") ? [] : entry.isDirectory() ? collect(`${path}/${entry.name}`) : /^(proof-manifest\.json|validation-receipt\.json)$/.test(entry.name) ? [] : [`${path}/${entry.name}`]);
const manifest = json(`${root}/proof-manifest.json`);

function validate(value: typeof manifest) {
  assert.equal(value.schema, "spec0012-phase4-proof/v1"); assert.equal(value.status, "PASS_WITH_RECORDED_LIMITATIONS"); assert.equal(value.base, base); assert.equal(value.head, base); assert.equal(value.branch, branch); assert.equal(value.worktree, process.cwd()); assert.equal(value.indexEmpty, true);
  assert.equal(git("rev-parse", "HEAD"), base); assert.equal(git("branch", "--show-current"), branch); assert.equal(git("diff", "--cached", "--name-only"), "");
  const dirty = [...new Set([...git("ls-files", "-m").split("\n"), ...git("ls-files", "--others", "--exclude-standard").split("\n")].filter(Boolean))].sort(); assert.deepEqual(dirty, expected); assert.deepEqual(value.dirtyPathAllowlist, expected); assert.deepEqual(value.actualDirtyPaths, expected); assert.deepEqual(value.changedExisting, changed); assert.deepEqual(value.added, added);
  assert.deepEqual(value.sources.map((binding: Binding) => binding.path), expected); value.sources.forEach(verify); assert.equal(value.sourceDigest, sha(JSON.stringify(value.sources))); verify(value.spec); assert.equal(value.spec.path, "docs/specs/0012-diamond-animator-guidance-assistant.md");
  const evidencePaths = collect(root).sort(); assert.deepEqual(value.evidence.map((binding: Binding) => binding.path), evidencePaths); assert.equal(new Set(value.evidence.map((binding: Binding) => binding.path)).size, value.evidence.length); value.evidence.forEach(verify);
  assert.deepEqual(value.limits, { model: "gpt-5.6-terra", reasoning: ["low", "medium", "high", "xhigh"], defaultReasoning: "medium", sessions: 50, messages: 200, sessionBytes: 1048576, databaseBytes: 33554432, contextMessages: 32, contextChars: 48000, inputTokens: 24000, outputTokens: 4000, jobDeadlineMs: 90000, searchDeadlineMs: 45000, activeJobs: 2, requestUsd: .15, webSearchCallUsd: .01, webSearchToolCalls: 2, processedSources: 8, displayedSources: 6, queryChars: 512, maxRetries: 0, store: false, localTools: [], searchTools: ["web_search"], arbitraryFetch: false, mediaInspection: false, projectMutation: false });
  assert.equal(value.proof.deterministicOracleAssertions, 47); assert.equal(value.proof.phase4BrowserAssertions, 23); assert.equal(value.proof.corruptRowBrowserAssertions, 27); assert.equal(value.proof.faultAssertions, 20); assert.equal(value.proof.inheritedAssistantBrowserAssertions, 90); assert.equal(value.proof.presentationAssertions, 60); assert.equal(value.proof.protectedBrowserAssertions, 21); assert.equal(value.proof.restartAssertions, 10); assert.equal(value.proof.repeatedBrowserAssertions, 33); assert.equal(value.proof.animatorSmokeAssertions, 11); assert.equal(value.proof.protectedOracleCount, 13); assert.deepEqual(value.proof.protectedDiff, []); assert.equal(value.proof.typecheck, "PASS"); assert.equal(value.proof.focusedLint, "PASS"); assert.equal(value.proof.diffCheck, "PASS"); assert.equal(value.proof.fullBuild, "INHERITED_BASELINE_FAILURE"); assert.equal(value.proof.focusedBuild, "PASS"); assert.equal(value.proof.deterministicProviderCalls, 1); assert.equal(value.proof.deterministicPaidCalls, 0); assert.equal(value.proof.correctionRealProviderCalls, 0); assert.equal(value.proof.correctionLiveSearchCalls, 0);
  const browser = json(`${root}/browser/result.json`); assert.equal(browser.status, "PASS"); assert.equal(browser.assertions.length, 23); assert.deepEqual(browser.errors, []); assert.deepEqual(browser.forbidden, []); assert.equal(browser.realProviderCalls, 0);
  const corruptRow = json(`${root}/corrupt-row/result.json`); assert.equal(corruptRow.status, "PASS"); assert.equal(corruptRow.assertionCount, 27); assert.equal(corruptRow.corruptRow.sha256Before, corruptRow.corruptRow.sha256After); assert.equal(corruptRow.corruptRow.exactCanonicalEquality, true); assert.equal(corruptRow.healthyRow.createdReasoning, "xhigh"); assert.equal(corruptRow.healthyRow.finalReasoning, "high"); assert.equal(corruptRow.capacity.rawRowCount.total, 50); assert.equal(corruptRow.capacity.rawRowCount.mutationRejected, true); assert.ok(corruptRow.capacity.rawBytes.unreadablePayloadChars > value.limits.databaseBytes); assert.equal(corruptRow.capacity.rawBytes.mutationRejected, true); assert.equal(corruptRow.requestLedger.deterministicProviderCalls, 1); assert.equal(corruptRow.requestLedger.realProviderCalls, 0); assert.equal(corruptRow.requestLedger.paidCalls, 0); assert.equal(corruptRow.requestLedger.liveSearchCalls, 0); assert.equal(corruptRow.requestLedger.externalRequests, 0); assert.equal(corruptRow.requestLedger.unrelatedApiRequests, 0); assert.deepEqual(corruptRow.errors, []); assert.deepEqual(corruptRow.forbidden, []);
  assert.deepEqual(value.proofCorrection.previousSeal.manifest, { path: `${root}/pre-storage-correction-proof-manifest.json`, bytes: 36978, sha256: "f29b22dbc6f112a4ca939bfaf908e5102710dfc6bac194954efb254c3a22a18a" }); assert.equal(value.proofCorrection.previousSeal.validation.sha256, "ec8f0f37158a9e672b4a5fe3b8c138016efe7078221a637c6adc39a6dcc1f96b"); assert.equal(value.proofCorrection.previousSeal.sourceDigest, "7dd51abe690337cd83535a6e41ec860f1fce1ffcdd0c58d095936b60f588c1d1"); verify(value.proofCorrection.previousSeal.manifest); verify(value.proofCorrection.previousSeal.validation);
  const acceptedRuntime = value.proofCorrection.acceptedRuntimeFreeze; assert.equal(acceptedRuntime.verifiedExact, true); assert.deepEqual(acceptedRuntime.sources.map((binding: Binding) => binding.path), ["src/lib/assistant/assistantStorage.ts", "src/components/assistant/useAssistantSessions.ts"]); assert.deepEqual(acceptedRuntime.sources.map((binding: Binding) => binding.sha256), ["c0c91ef607025f707d40b5af5e644aad12f0ef824a76e87f9e1279ee362cf80c", "1b3ae967b385ca2b5114b1883cb940c2af62ccc8fcfa7518b895d725c2bd2ac9"]); acceptedRuntime.sources.forEach(verify);
  const frozenSearchPaths = ["src/components/assistant/AssistantComposer.tsx", "src/components/assistant/AssistantConversation.tsx", "src/components/assistant/AssistantText.tsx", "src/components/assistant/diamondAssistant.module.css", "src/lib/assistant/assistantContracts.ts", "src/lib/assistant/assistantJobService.ts", "src/lib/assistant/assistantKnowledge.ts", "src/lib/assistant/assistantProvider.ts", "src/lib/assistant/assistantSearchPolicy.ts"]; assert.equal(value.proofCorrection.unchangedSearchProviderFreeze.verifiedExactAgainstPreviousSeal, true); assert.deepEqual(value.proofCorrection.unchangedSearchProviderFreeze.sources.map((binding: Binding) => binding.path), frozenSearchPaths); value.proofCorrection.unchangedSearchProviderFreeze.sources.forEach(verify); const prior = json(value.proofCorrection.previousSeal.manifest.path); const priorSources = new Map(prior.sources.map((binding: Binding) => [binding.path, binding])); for (const binding of value.proofCorrection.unchangedSearchProviderFreeze.sources) assert.deepEqual(binding, priorSources.get(binding.path), binding.path);
  assert.equal(value.proofCorrection.corruptRow.assertionCount, 27); assert.equal(value.proofCorrection.corruptRow.preservedCanonicalSha256, corruptRow.corruptRow.sha256After); assert.equal(value.proofCorrection.corruptRow.exactCanonicalEquality, true); assert.equal(value.proofCorrection.corruptRow.healthyChatCreated, true); assert.equal(value.proofCorrection.corruptRow.finalReasoning, "high"); assert.equal(value.proofCorrection.corruptRow.corruptKeyOverwriteRejected, true); assert.equal(value.proofCorrection.corruptRow.rawRowCountCapacityProven, true); assert.equal(value.proofCorrection.corruptRow.rawByteCapacityProven, true); assert.equal(value.proofCorrection.corruptRow.uiUsable, true); assert.equal(value.proofCorrection.corruptRow.realProviderCalls, 0); assert.equal(value.proofCorrection.corruptRow.paidCalls, 0); assert.equal(value.proofCorrection.corruptRow.liveSearchCalls, 0); verify(value.proofCorrection.corruptRow.result);
  const inherited = json(`${root}/regression-browsers/browser/result.json`); assert.equal(inherited.assertions.length, 90); assert.equal(inherited.accessibility.length, 6); for (const profile of inherited.accessibility) assert.deepEqual(profile.violations, []); assert.deepEqual(inherited.foreignMutations, []); assert.deepEqual(inherited.errors, []);
  const protectedBrowser = json(`${root}/regression-browsers/protected-browser/result.json`); assert.equal(protectedBrowser.beforeDigest, protectedBrowser.afterDigest); assert.deepEqual(protectedBrowser.network, []); assert.deepEqual(json(`${root}/regressions/result.json`).protectedDiff, []);
  const official = json(`${root}/official-evidence.json`); assert.equal(official.status, "PASS"); assert.equal(official.officialSourcesOnly, true); assert.equal(official.sources.length, 5); assert.equal(value.officialEvidence.sourceCount, 5); verify(value.officialEvidence.result);
  assert.deepEqual(value.live.initialConfiguredAuthorization, { authorizedSends: 2, actualSends: 2, retries: 0, result: "Greeting passed; exact search exposed the source-cap defect before publication" }); assert.equal(value.live.diagnosticAuthorization.authorizedRequests, 1); assert.equal(value.live.diagnosticAuthorization.actualRequests, 1); assert.equal(value.live.diagnosticAuthorization.retries, 0); assert.match(value.live.diagnosticAuthorization.terminalError, /source limit was exceeded/); assert.deepEqual(value.live.finalAuthorization, { authorizedUiSends: 1, actualUiSends: 1, retries: 0 }); assert.equal(value.live.totalUiSends, 5); assert.equal(value.live.totalDiagnosticApiRequests, 1); assert.equal(value.live.successfulAnswers, 2); assert.equal(value.live.greeting.visibleReply, true); assert.equal(value.live.greeting.modelAndZeroToolAssertionsPassed, true); assert.equal(value.live.search.terminalStatus, "done"); assert.equal(value.live.search.model, "gpt-5.6-terra"); assert.equal(value.live.search.reasoning, "medium"); assert.equal(value.live.search.toolCalls, 1); assert.equal(value.live.search.processedSourceCount, 8); assert.equal(value.live.search.displayedSources.length, 3); assert.equal(value.live.search.searchingTextObserved, true); assert.equal(value.live.search.finalizingObserved, true); assert.equal(value.live.search.answerPublished, true); assert.equal(value.live.search.citationsPublished, true); assert.equal(value.live.search.citationsPersistedAcrossReload, true); assert.equal(value.live.search.projectSentinelUnchanged, true); assert.deepEqual(value.live.search.errors, []); assert.deepEqual(value.live.search.externalBrowserRequests, []); assert.equal(value.live.billedUsageReceipt.finalSuccessfulRequestEstimatedCostUsd, .050754); assert.equal(value.live.billedUsageReceipt.finalSuccessfulRequestCeilingUsd, .15); assert.equal(value.live.billedUsageReceipt.priorFailedSearchToolCostReported, false); assert.equal(value.live.preconfigurationAttempts.uiSends, 2); assert.equal(value.live.preconfigurationAttempts.providerConfigured, false); assert.equal(value.live.preconfigurationAttempts.successfulAnswers, 0);
  const postmortem = json(`${root}/live/postmortem.json`); assert.equal(postmortem.status, "PASS_WITH_RECORDED_LIMITATION"); assert.equal(postmortem.configuredVerification.greetingCheckpointPassed, true); assert.equal(postmortem.configuredVerification.searchingTextObserved, true); assert.equal(postmortem.configuredVerification.searchTerminalAnswerObserved, false); assert.equal(postmortem.configuredRetries, 0);
  const diagnostic = json(`${root}/live/diagnostic.json`); assert.equal(diagnostic.status, "DIAGNOSTIC_TERMINAL_FAILURE"); assert.equal(diagnostic.requestCount, 1); assert.equal(diagnostic.retries, 0); assert.equal(diagnostic.terminalStatus, "failed"); assert.match(diagnostic.terminalError, /source limit was exceeded/); const finalSearch = json(`${root}/live/final-search-result.json`); assert.equal(finalSearch.status, "PASS"); assert.equal(finalSearch.requestCount, 1); assert.equal(finalSearch.retries, 0); assert.equal(finalSearch.terminalStatus, "done"); assert.equal(finalSearch.model, "gpt-5.6-terra"); assert.equal(finalSearch.reasoning, "medium"); assert.equal(finalSearch.toolCalls, 1); assert.equal(finalSearch.processedSourceCount, 8); assert.equal(finalSearch.displayedSources.length, 3); assert.equal(finalSearch.estimatedCostUsd, .050754); assert.equal(finalSearch.searchingTextObserved, true); assert.equal(finalSearch.finalizingObserved, true); assert.equal(finalSearch.citationsPersistedAcrossReload, true); assert.equal(finalSearch.projectSentinelUnchanged, true); assert.deepEqual(finalSearch.errors, []); assert.deepEqual(finalSearch.external, []);
  assert.equal(value.review.url, "http://127.0.0.1:58040/assistant"); assert.equal(value.review.production, true); assert.equal(value.review.healthStatus, 200); assert.equal(value.review.liveProviderConfigured, true); const health = spawnSync("curl", ["-s", "-o", "/dev/null", "-w", "%{http_code}", value.review.url], { encoding: "utf8" }); assert.equal(health.status, 0); assert.equal(health.stdout, "200");
  const reviewServer = json(`${root}/review-server.json`); assert.equal(reviewServer.pid, value.review.port === 58040 ? Number(execFileSync("lsof", ["-nP", "-iTCP:58040", "-sTCP:LISTEN", "-t"], { encoding: "utf8" }).trim()) : -1); assert.equal(reviewServer.credentialFileIgnored, true); assert.equal(reviewServer.credentialFileTracked, false); assert.equal(reviewServer.credentialContentsDisplayed, false); assert.equal(reviewServer.sha256EqualityVerified, true); assert.equal(git("check-ignore", ".env.local"), ".env.local"); assert.equal(git("ls-files", ".env.local"), "");
  const provider = readFileSync("src/lib/assistant/assistantProvider.ts", "utf8"); assert.match(provider, /maxRetries: 0/); assert.match(provider, /type: "web_search"/); assert.match(provider, /tool_choice: "required"/); assert.match(provider, /max_tool_calls: ASSISTANT_SEARCH_LIMITS\.toolCalls/); assert.match(provider, /store: false/); assert.doesNotMatch(provider, /fetch\(/);
  const conversation = readFileSync("src/components/assistant/AssistantConversation.tsx", "utf8"); assert.match(conversation, /Searching the web for \$\{live\.events\.at\(-1\)\?\.topic\}…/); assert.match(conversation, /aria-label="Sources"/); assert.doesNotMatch(conversation, /<img|<Image/);
  assert.deepEqual(git("diff", "--name-only", base, "--", ...value.protected.families).split("\n").filter(Boolean), []); assert.deepEqual(value.protected.diffFromActivationBase, []); assert.equal(value.protected.projectSentinelsUnchanged, true); assert.equal(value.protected.externalBrowserRequests, 0); assert.equal(value.protected.unrelatedApiRequests, 0);
  assert.equal(value.humanAcceptance, "accepted by Arthur and Project Manager before this technical-proof correction"); for (const key of ["controlPlaneUpdated", "gitPublication", "staged", "committed", "pushed", "deployed", "laterPhaseStarted"]) assert.equal(value[key], false); assert.equal(value.limitations.length, 5); assert.match(value.ownership, /Sole correction Spec Executor stops/); assert.match(value.cleanupPlan, /D-0054/);
}

validate(manifest);
const mutations: Array<[string, (candidate: typeof manifest) => void]> = [
  ["base", value => { value.base = "0".repeat(40); }], ["path", value => { value.dirtyPathAllowlist.pop(); }], ["source", value => { value.sources[0].sha256 = "0".repeat(64); }], ["evidence", value => { value.evidence[0].sha256 = "0".repeat(64); }], ["missing evidence", value => { value.evidence.pop(); }],
  ["model", value => { value.limits.model = "other"; }], ["tool calls", value => { value.limits.webSearchToolCalls = 3; }], ["sources", value => { value.limits.processedSources = 9; }], ["displayed", value => { value.limits.displayedSources = 7; }], ["query", value => { value.limits.queryChars = 1024; }], ["search deadline", value => { value.limits.searchDeadlineMs = 90000; }], ["store", value => { value.limits.store = true; }], ["retry", value => { value.limits.maxRetries = 1; }],
  ["configured sends", value => { value.live.initialConfiguredAuthorization.actualSends = 3; }], ["configured retry", value => { value.live.initialConfiguredAuthorization.retries = 1; }], ["final sends", value => { value.live.finalAuthorization.actualUiSends = 2; }], ["final retry", value => { value.live.finalAuthorization.retries = 1; }], ["false live answer", value => { value.live.search.answerPublished = false; }], ["false citations", value => { value.live.search.citationsPublished = false; }], ["cost", value => { value.live.billedUsageReceipt.finalSuccessfulRequestEstimatedCostUsd = .16; }], ["proof", value => { value.proof.deterministicOracleAssertions = 1; }], ["corrupt proof", value => { value.proofCorrection.corruptRow.exactCanonicalEquality = false; }], ["runtime freeze", value => { value.proofCorrection.acceptedRuntimeFreeze.sources[0].sha256 = "0".repeat(64); }], ["search freeze", value => { value.proofCorrection.unchangedSearchProviderFreeze.sources[0].sha256 = "0".repeat(64); }], ["protected", value => { value.protected.diffFromActivationBase.push("docs/README.md"); }], ["acceptance", value => { value.humanAcceptance = "pending"; }], ["control plane", value => { value.controlPlaneUpdated = true; }], ["publication", value => { value.gitPublication = true; }], ["limitation", value => { value.limitations.shift(); }],
];
for (const [name, mutate] of mutations) { const candidate = structuredClone(manifest); mutate(candidate); assert.throws(() => validate(candidate), `must reject ${name}`); }
const result = { status: "PASS", manifestSha256: sha(readFileSync(`${root}/proof-manifest.json`)), sourceDigest: manifest.sourceDigest, sourceFiles: manifest.sources.length, evidenceFiles: manifest.evidence.length, mutationRejections: mutations.map(([name]) => name), initialConfiguredLiveSends: 2, diagnosticRequests: 1, finalLiveSends: 1, retries: 0, liveSearchCitationQualityProven: true, finalSuccessfulRequestEstimatedCostUsd: .050754, corruptRowAssertions: 27, corruptRowCanonicalSha256: manifest.proofCorrection.corruptRow.preservedCanonicalSha256, correctionRealProviderCalls: 0, correctionPaidCalls: 0, correctionLiveSearchCalls: 0, acceptedRuntimeFreezeVerified: true, unchangedSearchProviderFreezeVerified: true };
writeFileSync(`${root}/validation-receipt.json`, JSON.stringify(result, null, 2), { flag: "wx" }); console.log(JSON.stringify(result));
