import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import ts from "typescript";
const root="output/spec-0012/phase-2-final-correction",priorRoot="output/spec-0012/phase-2-correction",originalRoot="output/spec-0012/phase-2";
const base="652431396e78370f3dfb7549294e66d154c3b7d4",priorHash="68953d8900f793676cdb5eaa611a449112664b4f1af504690cac9a682cd5e6f5",originalHash="63a87f3e832a200a52c18115fa9ed7533eaf1fb4b5cfc01438e2c1f8c1b3c8ec";
const sha=(v:string|Buffer)=>createHash("sha256").update(v).digest("hex"),json=(path:string)=>JSON.parse(readFileSync(path,"utf8")),git=(...args:string[])=>execFileSync("git",args,{encoding:"utf8"}).trim();
type Binding={path:string;bytes:number;sha256:string};const verify=(b:Binding)=>{assert.ok(!b.path.startsWith("/")&&!b.path.includes("..")&&!b.path.includes(".env"));const bytes=readFileSync(b.path);assert.equal(bytes.length,b.bytes);assert.equal(sha(bytes),b.sha256,b.path)};
const prior=json(`${priorRoot}/proof-manifest.json`),original=json(`${originalRoot}/proof-manifest.json`);assert.equal(sha(readFileSync(`${priorRoot}/proof-manifest.json`)),priorHash);assert.equal(sha(readFileSync(`${originalRoot}/proof-manifest.json`)),originalHash);
const additions=["phase2FinalCorrectionOracle","phase2FinalCorrectionBrowser","runPhase2FinalCorrectionProof","recordPhase2FinalCorrectionProof","validatePhase2FinalCorrectionProof"].map(n=>`scripts/spec0012-assistant/${n}.ts`).sort();
const changed=["scripts/spec0012-assistant/phase2Oracle.ts","src/lib/assistant/assistantJobService.ts","src/lib/assistant/assistantProvider.ts"].sort();const expected=[...prior.dirtyPathAllowlist,...additions].sort();assert.equal(expected.length,34);
const limits={sessions:50,messages:200,sessionBytes:1048576,databaseBytes:33554432,contextMessages:32,contextChars:48000,inputTokens:24000,outputTokens:4000,deadlineMs:90000,activePerSession:1,activeEnvironment:2};
const policy={model:"gpt-5.6-terra",reasoning:["low","medium","high","xhigh"],defaultReasoning:"medium",requestUsd:.15,inputTokens:24000,outputTokens:4000,deadlineMs:90000,maxRetries:0,activeJobs:2,sessions:50,jobMemory:500,dailyCap:null,monthlyCap:null,ledgerGate:false,tools:[],store:false,localOnly:true,automaticResends:false,usageReporting:true};
const limitations=["Live provider access/answer quality unproven: executor automated calls are zero; no claim about Arthur manual usage","Full build retains unchanged app/dev/ai-costs/lifetime/page.tsx PageProps/searchParams failure; focused production build passes","Full lint retains inherited 5 errors and 81 warnings in unchanged base files; focused lint passes","Historical Animator transient reveal observation remains unproven; focused Animator smoke and protected byte equality pass","Chromium/emulated profiles only; no physical-device or non-Chromium claim","Canonical control plane untouched; acceptance, CPA propagation and publication remain separate","Cumulative local spending cap intentionally absent under Arthur authority; preserved request/job/token boundaries remain"];
const manifest=json(`${root}/proof-manifest.json`);
type Adapter={name:string;path:string;sourceSha256:string;generated:string;generatedSha256:string;assertionsRemoved:number;changes:string[]};
const validateAdapters=(entries:Adapter[],overrides:Record<string,string>={})=>{
 const names=["phase2Oracle","phase2CorrectionOracle","phase2BrowserProof","phase2CorrectionBrowser","phase2ProtectedBrowser","phase2RestartProof","phase2FaultProof","phase2AnimatorSmoke","phase2Regressions","phase2BuildProof"];
 assert.deepEqual(entries.map(e=>e.name),names);
 for(const entry of entries){assert.equal(entry.path,`scripts/spec0012-assistant/${entry.name}.ts`);assert.equal(entry.generated,resolve(root,"adapters",`${entry.name}.mjs`));const source=readFileSync(entry.path,"utf8");assert.equal(entry.sourceSha256,sha(source));
  const redirected=source.replaceAll("phase-2-correction","phase-2-final-correction").replaceAll("phase2-correction-build-","phase2-final-correction-build-").replace(/(from\s+["'])(\.[^"']+)(["'])/g,(_all,start,target,end)=>`${start}${resolve("scripts/spec0012-assistant",target)}${end}`);
  const expectedJs=ts.transpileModule(redirected,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
  const actualJs=overrides[entry.name]??readFileSync(entry.generated,"utf8");assert.equal(entry.generatedSha256,sha(actualJs));assert.equal(actualJs,expectedJs,"only authorized evidence-root/import transformation; all source assertions retained");assert.equal(entry.assertionsRemoved,0);
  assert.deepEqual(entry.changes,["separate final evidence directory/build ledger labels","relative imports resolved from original source directory"]);
 }
};
const validate=(m:typeof manifest)=>{
 assert.equal(m.schema,"spec0012-phase2-final-correction-proof/v1");assert.equal(m.status,"PASS_WITH_RECORDED_LIMITATIONS");assert.equal(m.base,base);assert.equal(m.head,base);assert.equal(git("rev-parse","HEAD"),base);assert.equal(m.branch,"");assert.equal(git("branch","--show-current"),"");assert.equal(m.worktree,"/Users/arthurcarlin/.codex/worktrees/a996/stick-animation-app");assert.equal(m.worktree,process.cwd());assert.equal(m.indexEmpty,true);assert.equal(git("diff","--cached","--name-only"),"");
 const dirty=[...new Set([...git("ls-files","-m").split("\n"),...git("ls-files","--others","--exclude-standard").split("\n")].filter(Boolean))].sort();assert.deepEqual(dirty,expected);assert.deepEqual(m.dirtyPathAllowlist,expected);assert.deepEqual(m.actualDirtyPaths,expected);assert.deepEqual(m.sources.map((x:Binding)=>x.path),expected);assert.deepEqual(m.changedExisting,changed);assert.deepEqual(m.added,additions);
 const bindings=[...m.sources,...m.evidence] as Binding[];assert.equal(new Set(bindings.map(b=>b.path)).size,bindings.length);bindings.forEach(verify);assert.equal(m.sourceDigest,sha(JSON.stringify(m.sources)));
 const inventory=(path:string):string[]=>readdirSync(path,{withFileTypes:true}).flatMap(e=>e.name==="baseline-sources"||e.name.startsWith("profile-")?[]:e.isDirectory()?inventory(`${path}/${e.name}`):/^(proof-manifest\.json|validation-receipt\.json|independent-validation.*|Implementation-Review-Packet\.md|review-server\.log)$/.test(e.name)?[]:[`${path}/${e.name}`]);assert.deepEqual(m.evidence.map((b:Binding)=>b.path),[...inventory(root),...["full","focused"].map(k=>`output/spec-0012/phase-1-correction/environment/phase2-final-correction-build-${k}-network.jsonl`)].sort());
 assert.equal(m.preservation.originalManifest.path,`${originalRoot}/proof-manifest.json`);assert.equal(m.preservation.originalManifest.sha256,originalHash);verify(m.preservation.originalManifest);assert.equal(m.preservation.priorManifest.path,`${priorRoot}/proof-manifest.json`);assert.equal(m.preservation.priorManifest.sha256,priorHash);verify(m.preservation.priorManifest);assert.equal(m.preservation.originalEvidenceBindings,67);assert.equal(m.preservation.priorEvidenceBindings,101);assert.equal(m.preservation.baseline.path,`${root}/baseline-bindings.json`);verify(m.preservation.baseline);
 [...original.evidence,...prior.evidence,original.spec].forEach(verify);assert.deepEqual(m.preservation.priorSourceSnapshots.map((b:Binding)=>b.path),prior.sources.map((b:Binding)=>b.path));
 for(const item of prior.sources as Binding[]){const snapshot=m.preservation.priorSourceSnapshots.find((b:Binding)=>b.path===item.path);assert.equal(snapshot.backupPath,`${root}/baseline-sources/${item.path}.snapshot`);assert.equal(snapshot.sha256,item.sha256);assert.equal(snapshot.bytes,item.bytes);verify({...item,path:snapshot.backupPath});if(!changed.includes(item.path))verify(item)}
 for(const item of original.sources as Binding[]){const snapshot=prior.original.sourceSnapshots.find((b:Binding)=>b.path===item.path);verify({...item,path:snapshot.backupPath})}
 assert.deepEqual(m.limits,limits);assert.deepEqual(m.costPolicy,policy);assert.deepEqual(m.limitations,limitations);assert.equal(m.authority.sourceTask,"01a0b45e-dd0b-73c3-b42d-d5b49dced309");assert.equal(m.authority.phase,2);assert.match(m.authority.scope,/Arthur explicitly authorizes complete removal/);assert.match(m.authority.modeLimitation,/no claim Plan mode was active/);assert.match(m.authority.ownership,/sole Spec Executor/);assert.match(m.authority.canonicalConflict,/canonical docs remain untouched/);
 const results=["oracle.json","correction-oracle.json","final-correction-oracle.json","browser/result.json","presentation/result.json","repeated-browser/result.json","protected-browser/result.json","restart/result.json","faults/result.json","animator-smoke/result.json","regressions/result.json","build/result.json","production-verification.json","production-smoke.json"];
 for(const path of results){const proof=json(`${root}/${path}`);assert.equal(proof.status,"PASS");assert.equal(proof.realProviderCalls,0)}
 const general=json(`${root}/oracle.json`),timing=json(`${root}/correction-oracle.json`),oracle=json(`${root}/final-correction-oracle.json`),browser=json(`${root}/repeated-browser/result.json`),sessions=json(`${root}/browser/result.json`),presentation=json(`${root}/presentation/result.json`),protectedProof=json(`${root}/protected-browser/result.json`),animator=json(`${root}/animator-smoke/result.json`),regression=json(`${root}/regressions/result.json`);
 assert.ok(general.assertions.length>=112);assert.equal(timing.assertions.length,23);assert.equal(oracle.assertions.length,38);assert.equal(oracle.successfulRepeatedProviderCalls,120);assert.equal(oracle.sdkTransportDoubleCalls,122);assert.ok(oracle.formerReservationsUsd>5&&oracle.simulatedUsageUsd>5);assert.deepEqual(oracle.scenarioResults.map((x:{scenario:string})=>x.scenario),["exhausted","malformed","locked","absent"]);assert.ok(oracle.scenarioResults.every((x:{completedRequests:number;legacyBytesUnchanged:boolean})=>x.completedRequests===30&&x.legacyBytesUnchanged));assert.equal(oracle.actualReviewLedgerUntouched,true);
 assert.equal(browser.posts,12);assert.equal(browser.sdkTransportDoubleCalls,12);assert.ok(browser.formerReservationsUsd>.6);assert.equal(browser.legacyLedgerUnchanged,true);assert.deepEqual(browser.errors,[]);assert.deepEqual(browser.forbidden,[]);assert.ok(browser.assertions.length>=33);
 assert.equal(sessions.assertions.length,90);assert.deepEqual(sessions.foreignMutations,[]);assert.deepEqual(sessions.errors,[]);assert.equal(sessions.accessibility.length,6);for(const item of sessions.accessibility)assert.deepEqual(item.violations,[]);
 assert.equal(presentation.assertions.length,60);assert.deepEqual(presentation.errors,[]);assert.deepEqual(presentation.forbidden,[]);assert.equal(presentation.nativeScrollbarPaintingEnabled,true);assert.deepEqual(presentation.documentScroll,{scrollY:0,scrollHeight:814,clientHeight:814,rootWidth:1440,viewportWidth:1440});assert.deepEqual(presentation.thinkingStyle,presentation.acceptedStyle);assert.deepEqual(presentation.rawAcceptedStyle,animator.statusStyle);assert.ok(presentation.visibleFinalizingMs>=2500&&presentation.visibleFinalizingMs<3800);assert.ok(presentation.narrationDelayMs>=7900&&presentation.narrationDelayMs<10000);
 assert.equal(protectedProof.assertions.length,21);assert.equal(protectedProof.beforeDigest,protectedProof.afterDigest);assert.deepEqual(protectedProof.network,[]);assert.equal(json(`${root}/restart/result.json`).assertions.length,10);assert.equal(json(`${root}/restart/result.json`).actualBrowserRelaunch,true);assert.equal(json(`${root}/faults/result.json`).assertions.length,20);assert.equal(animator.assertions,11);assert.deepEqual(animator.errors,[]);assert.deepEqual(animator.externalRequests,[]);assert.deepEqual(animator.assistantRequests,[]);assert.equal(regression.receipts.length,13);assert.equal(git("diff","--name-only",base,"--",...regression.protectedFamilies,"app/ScrollbarActivity.tsx"),"");
 const source=readFileSync("src/lib/assistant/assistantProvider.ts","utf8");assert.doesNotMatch(source,/budget|dayUsd|monthUsd|node:fs|node:path|reserveBudget/i);assert.match(source,/maximumCostUsd <= ASSISTANT_PRICE.requestUsd/);assert.match(source,/maxRetries: 0, timeout: ASSISTANT_LIMITS.deadlineMs/);
 validateAdapters(json(`${root}/adapter-bindings.json`));
 for(const id of ["typescript","focused-lint","diff-check"])assert.equal(json(`${root}/receipts/${id}.json`).exitCode,0);const lint=json(`${root}/receipts/lint-nonregression.json`);assert.equal(lint.errors,5);assert.equal(lint.warnings,81);assert.deepEqual(lint.newFindings,[]);for(const b of lint.verifiedUnchangedFiles)assert.deepEqual(readFileSync(b.path),execFileSync("git",["show",`${base}:${b.path}`]));const build=json(`${root}/build/result.json`);assert.equal(build.focused.status,"PASS");assert.equal(build.full.status,"INHERITED_BASELINE_FAILURE");
 const production=json(`${root}/production-verification.json`);assert.equal(production.mode,"production");assert.equal(production.suites.length,7);assert.ok(production.buildId);assert.equal(production.sourceDigest,sha(JSON.stringify(prior.sources.map((b:Binding)=>({path:b.path,sha256:sha(readFileSync(b.path))})))));
 for(const path of [`${root}/network-proof.jsonl`,...["full","focused"].map(k=>`output/spec-0012/phase-1-correction/environment/phase2-final-correction-build-${k}-network.jsonl`)])assert.deepEqual(readFileSync(path,"utf8").split("\n").filter(Boolean).map(x=>JSON.parse(x)).filter(x=>x.result==="denied"),[]);
 assert.deepEqual(m.proof,{successfulRepeatedProviderCalls:120,sdkOracleTransportDoubles:122,repeatedUiQuestions:12,sdkUiTransportDoubles:12,formerReservationTotalUsd:oracle.formerReservationsUsd,simulatedUsageTotalUsd:oracle.simulatedUsageUsd,oldBudgetRuntimePathsAbsent:true,legacyLedgerInert:true,realProviderCalls:0,paidCalls:0,automatedCostUsd:0});
 assert.deepEqual(m.review,{url:"http://127.0.0.1:57970/assistant",port:57970,production:true,existingCredentialPreserved:true,automatedProviderCallsAfterEnablement:0});const server=json(`${root}/review-server.json`),config=json(`${root}/review-config.json`);assert.equal(server.cwd,process.cwd());assert.equal(server.port,57970);assert.equal(server.mode,"production");assert.ok(Number.isInteger(server.pid)&&server.pid>0);assert.equal(config.credentialFilePreserved,true);assert.equal(config.credentialPrintedOrHashed,false);assert.equal(config.automatedProviderCallsAfterEnablement,0);assert.equal(git("ls-files",".env.local"),"");assert.equal(git("check-ignore",".env.local"),".env.local");
 assert.equal(m.humanAcceptance,"pending Arthur and Project Manager");for(const key of ["controlPlaneUpdated","gitPublication","staged","committed","pushed","deployed","laterPhaseStarted"])assert.equal(m[key],false);assert.match(m.ownership,/Sole Spec Executor stops/);assert.match(m.cleanupPlan,/D-0054/);
};
validate(manifest);
const mutations:Array<[string,(m:typeof manifest)=>void]>=[
 ["base",m=>{m.base="0".repeat(40)}],["paths",m=>{m.dirtyPathAllowlist.pop()}],["source",m=>{m.sources[0].sha256="0".repeat(64)}],["evidence",m=>{m.evidence[0].sha256="0".repeat(64)}],["missing evidence",m=>{m.evidence.pop()}],["prior seal",m=>{m.preservation.priorManifest.sha256="0".repeat(64)}],["original seal",m=>{m.preservation.originalManifest.sha256="0".repeat(64)}],["snapshots",m=>{m.preservation.priorSourceSnapshots.pop()}],["runtime boundary",m=>{m.changedExisting.push("app/globals.css")}],["daily cap",m=>{m.costPolicy.dailyCap=.6}],["monthly cap",m=>{m.costPolicy.monthlyCap=5}],["ledger",m=>{m.costPolicy.ledgerGate=true}],["per-request cap",m=>{m.costPolicy.requestUsd=15}],["input cap",m=>{m.costPolicy.inputTokens=48000}],["output cap",m=>{m.costPolicy.outputTokens=8000}],["model",m=>{m.costPolicy.model="other"}],["retry",m=>{m.costPolicy.maxRetries=1}],["concurrency",m=>{m.costPolicy.activeJobs=3}],["job cap",m=>{m.costPolicy.jobMemory=9999}],["local access",m=>{m.costPolicy.localOnly=false}],["tools",m=>{m.costPolicy.tools.push("search")}],["store",m=>{m.costPolicy.store=true}],["usage",m=>{m.costPolicy.usageReporting=false}],["repeat proof",m=>{m.proof.successfulRepeatedProviderCalls=12}],["UI proof",m=>{m.proof.repeatedUiQuestions=1}],["paid",m=>{m.proof.paidCalls=1}],["cost",m=>{m.proof.automatedCostUsd=.1}],["acceptance",m=>{m.humanAcceptance="accepted"}],["control plane",m=>{m.controlPlaneUpdated=true}],["publication",m=>{m.gitPublication=true}],["later phase",m=>{m.laterPhaseStarted=true}],["limitations",m=>{m.limitations[0]="Live quality proven"}],
];
for(const[name,mutate]of mutations){const candidate=structuredClone(manifest);mutate(candidate);assert.throws(()=>validate(candidate),`must reject ${name}`)}
const adapters:Adapter[]=json(`${root}/adapter-bindings.json`);assert.throws(()=>validateAdapters(adapters.slice(1)),"missing adapter rejected");const changedAdapter=structuredClone(adapters);const altered=readFileSync(changedAdapter[0].generated,"utf8")+"\n// Unauthorized generated body change\n";changedAdapter[0].generatedSha256=sha(altered);assert.throws(()=>validateAdapters(changedAdapter,{[changedAdapter[0].name]:altered}),"changed generated body rejected even with updated hash");
const result={status:"PASS",manifestSha256:sha(readFileSync(`${root}/proof-manifest.json`)),sourceDigest:manifest.sourceDigest,sourceFiles:expected.length,evidenceFiles:manifest.evidence.length,originalManifestSha256:originalHash,priorManifestSha256:priorHash,mutationRejections:[...mutations.map(([name])=>name),"missing adapter","changed adapter with updated hash"],executorPaidCalls:0};if(!process.argv.includes("--read-only"))writeFileSync(`${root}/validation-receipt.json`,JSON.stringify(result,null,2),{flag:"wx"});console.log(JSON.stringify(result));
