import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { chromium } from 'playwright-core';
import { AssistantTranscriptionService } from '../../../src/lib/assistant/assistantTranscriptionService.ts';
import { validateWav } from '../../../src/lib/assistant/assistantDictationContract.ts';
import { DiamondAssistantJobService } from '../../../src/lib/assistant/assistantJobService.ts';
import { fixtureResult } from '../phase2Fixtures.ts';
const origin='http://127.0.0.1:58070';const output='output/spec-0012/phase-5/browser';mkdirSync(output,{recursive:true});
const accessibility:Record<string,unknown>[]=[];const assertions:string[]=[];const errors:string[]=[];const requests:Record<string,unknown>[]=[];const screenshots:string[]=[];const storageDigests:Record<string,string>={};
const check=(condition:unknown,name:string)=>{assert.ok(condition,name);assertions.push(name);};const equal=(actual:unknown,expected:unknown,name:string)=>{assert.deepEqual(actual,expected,name);assertions.push(name);};
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
let transcriptions=0,guidance=0,mode='success';let release:()=>void=()=>{};let maxRecorded=0;
const service=new AssistantTranscriptionService(async(_,options)=>{
 transcriptions++; const form=options!.body as FormData;const file=form.get('file') as File;const bytes=new Uint8Array(await file.arrayBuffer());const audio=validateWav(bytes,file.type);maxRecorded=Math.max(maxRecorded,audio.seconds);requests.push({kind:'transcription-double',bytes:bytes.length,seconds:audio.seconds,model:form.get('model')});bytes.fill(0);
 if(mode==='hold')await new Promise<void>((resolve,reject)=>{release=resolve;options!.signal!.addEventListener('abort',()=>reject(new Error('cancelled-double')),{once:true});});
 if(mode==='failure')return new Response('',{status:503});
 if(mode==='empty')return Response.json({text:''});
 if(mode==='oversize')return Response.json({text:'a'.repeat(6001)});
 return Response.json({text:'Where can I find the drawing tools?'});
},()=> 'deterministic-fixture');
const jobs=new DiamondAssistantJobService(async request=>{guidance++;return fixtureResult(request,'The drawing tools are in the workspace.','Drawing tools');},55000,100);
interface Probe { tracks:MediaStreamTrack[];contexts:AudioContext[];calls:number;analyserCalls:number;peaks:number[];nodes:number;closedPorts:number;rawWrites:number;urls:number;permission:string;release?:()=>void;limits:(()=>void)[];deadlines:(()=>void)[];permissions:(()=>void)[] }
declare global { interface Window { __p5:Probe } }
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--disable-background-networking','--disable-component-update','--disable-sync','--no-first-run']});
try{
 const context=await browser.newContext({viewport:{width:1440,height:900},permissions:['microphone']});
 await context.addInitScript(()=>{
  const p:Probe={tracks:[],contexts:[],calls:0,analyserCalls:0,peaks:[],nodes:0,closedPorts:0,rawWrites:0,urls:0,permission:'allow',limits:[],deadlines:[],permissions:[]};window.__p5=p;
  const gum=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
  navigator.mediaDevices.getUserMedia=async options=>{p.calls++;if(p.permission==='denied')throw new DOMException('denied','NotAllowedError');if(p.permission==='missing')throw new DOMException('missing','NotFoundError');if(p.permission==='busy')throw new DOMException('busy','NotReadableError');if(p.permission==='hold')await new Promise<void>(r=>p.release=r);const s=await gum(options);p.tracks.push(...s.getTracks());if(p.permission==='silent')s.getTracks().forEach(t=>t.enabled=false);return s;};
  window.AudioContext=new Proxy(window.AudioContext,{construct(target,args){const ctx=Reflect.construct(target,args) as AudioContext;p.contexts.push(ctx);return ctx;}});
  window.AudioWorkletNode=new Proxy(window.AudioWorkletNode,{construct(target,args){const node=Reflect.construct(target,args) as AudioWorkletNode;p.nodes++;const close=node.port.close.bind(node.port);node.port.close=()=>{p.closedPorts++;close();};return node;}});
  const sample=AnalyserNode.prototype.getFloatTimeDomainData;AnalyserNode.prototype.getFloatTimeDomainData=function(array){sample.call(this,array);p.analyserCalls++;let peak=0;for(const value of array)peak=Math.max(peak,Math.abs(value));if(p.peaks.length<1000)p.peaks.push(peak);};
  const timeout=window.setTimeout.bind(window);window.setTimeout=((fn:TimerHandler,ms?:number,...args:unknown[])=>{if(ms===120000 && typeof fn==='function')p.limits.push(()=>fn());if(ms===30000 && typeof fn==='function')p.permissions.push(()=>fn());if(ms===45000 && typeof fn==='function')p.deadlines.push(()=>fn());return timeout(fn,ms,...args);}) as typeof window.setTimeout;
  const url=URL.createObjectURL;URL.createObjectURL=function(blob){p.urls++;return url(blob);};
  const raw=(x:unknown):boolean=>x instanceof Blob||x instanceof ArrayBuffer||ArrayBuffer.isView(x)||(typeof x==='string'&&/data:audio|blob:http/.test(x))||(!!x&&typeof x==='object'&&Object.values(x).some(raw));
  const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(raw(args))p.rawWrites++;return Reflect.apply(put,this,args);};
  const set=Storage.prototype.setItem;Storage.prototype.setItem=function(...args){if(raw(args))p.rawWrites++;return Reflect.apply(set,this,args);};
 });
 await context.route('**/*',async route=>{
  const req=route.request();const url=new URL(req.url());
  if(url.origin!==origin){errors.push(`external:${url.origin}`);await route.abort();return;}
  if(url.pathname==='/api/diamond-assistant-transcription'){
   const id=req.headers()['x-dictation-id'];requests.push({method:req.method(),path:url.pathname,id:id??url.searchParams.get('id')});
   const value=req.method()==='DELETE'?service.cancel(new Request(req.url(),{method:'DELETE',headers:{host:'127.0.0.1:58070'}})):await service.transcribe(new Request(req.url(),{method:'POST',headers:{host:'127.0.0.1:58070','content-type':'audio/wav','x-dictation-id':id},body:new Uint8Array(req.postDataBuffer()!)}));
   try{await route.fulfill({status:value.status,contentType:'application/json',body:await value.text()});}catch{}return;
  }
  if(url.pathname==='/api/diamond-assistant'){
   const value=req.method()==='POST'?jobs.submit(req.postDataJSON()):req.method()==='DELETE'?jobs.cancelRequest(req.postDataJSON()):jobs.get(url.searchParams.get('jobId')!,url.searchParams.get('sessionId')!);await route.fulfill({status:value?(req.method()==='POST'?202:200):404,contentType:'application/json',body:JSON.stringify(value??{})});return;
  }
  if(url.pathname.startsWith('/api/')){errors.push(`unrelated:${url.pathname}`);await route.abort();return;}await route.continue();
 });
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(`${origin}/assistant`);await page.getByRole('button',{name:'New Chat',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('button[aria-describedby="assistant-sessions-note"]')?.hasAttribute('disabled'));
 const input=page.getByLabel('Message the Assistant');const mic=page.getByRole('button',{name:'Dictate a message',exact:true});
 const waitIdle=()=>page.waitForFunction(()=>!document.querySelector('[data-dictation-phase]'));
 const record=async()=>{await mic.click();await page.getByRole('button',{name:'Stop dictation',exact:true}).waitFor();await page.waitForTimeout(1700);};
 const snap=async(name:string)=>{await page.screenshot({path:`${output}/${name}.png`});screenshots.push(name);};
 const cleanup=async(name:string)=>{await page.waitForFunction(()=>window.__p5.tracks.every(t=>t.readyState==='ended')&&window.__p5.contexts.every(c=>c.state==='closed'));const p=await page.evaluate(()=>({tracks:window.__p5.tracks.length,live:window.__p5.tracks.filter(t=>t.readyState==='live').length,open:window.__p5.contexts.filter(c=>c.state!=='closed').length,nodes:window.__p5.nodes,closed:window.__p5.closedPorts,raw:window.__p5.rawWrites,urls:window.__p5.urls}));check(p.live===0&&p.open===0&&p.nodes===p.closed&&p.raw===0&&p.urls===0,name);};
 const storage=async()=>page.evaluate(async()=>{const all:Record<string,unknown>={local:{...localStorage},session:{...sessionStorage}};for(const entry of await indexedDB.databases()){const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(entry.name!);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const stores:Record<string,unknown>={};for(const name of db.objectStoreNames){stores[name]=await new Promise((resolve,reject)=>{const r=db.transaction(name).objectStore(name).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}all[entry.name!]=stores;db.close();}return all;});
 await page.evaluate(()=>localStorage.setItem('phase5-protected-project-sentinel','unchanged'));
 const initialStorage=await storage();storageDigests.before=hash(initialStorage);await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));equal(await page.locator('[role="status"]').allTextContents(),['',''],'idle page lifecycle never claims a recording was cancelled');equal(await page.evaluate(()=>window.__p5.calls),0,'mount requests no microphone permission');await input.fill('My existing draft.');await record();
 await page.waitForFunction(()=>[...document.querySelectorAll('[aria-label="Live microphone waveform"] span')].some(el=>parseFloat((el as HTMLElement).style.height)>2));
 const recordingMeasured=performance.now();
 const a=await page.locator('[aria-label="Live microphone waveform"] span').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).style.height));await page.waitForTimeout(150);const b=await page.locator('[aria-label="Live microphone waveform"] span').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).style.height));
 const samples=await page.evaluate(()=>({calls:window.__p5.analyserCalls,peak:Math.max(...window.__p5.peaks)}));const sampleInspectionMs=performance.now()-recordingMeasured;check(samples.calls>10&&samples.peak>0,'fake media device produces actual sampled audio');check(JSON.stringify(a)!==JSON.stringify(b)||new Set(a).size>1,'waveform derives responsive nonuniform bars from analyser samples');await page.waitForFunction(()=>[...document.querySelectorAll('[aria-label="Live microphone waveform"] span')].some(el=>parseFloat((el as HTMLElement).style.height)>5));await snap('desktop-recording');
 await page.getByRole('button',{name:'Cancel dictation'}).click();await waitIdle();await cleanup('Cancel releases tracks/context/worklet; no URLs or raw storage');equal(await input.inputValue(),'My existing draft.','Cancel preserves existing text');equal(transcriptions,0,'Cancel makes zero transcription calls');storageDigests.afterCancel=hash(await storage());equal(await storage(),initialStorage,'Cancel leaves every storage digest unchanged');
 await record();const stopStarted=performance.now();await page.getByRole('button',{name:'Stop dictation'}).click();await waitIdle();await cleanup('Stop completion releases all resources');const stopCompletionMs=performance.now()-stopStarted;check(stopCompletionMs<5000,'deterministic Stop-to-editable-text completes within five seconds');equal(transcriptions,1,'Stop submits exactly one transcription');equal(guidance,0,'transcription never automatically Sends');equal(await input.inputValue(),'My existing draft. Where can I find the drawing tools?','transcript appends to editable draft');storageDigests.afterTranscript=hash(await storage());equal(storageDigests.afterTranscript,storageDigests.before,'unsent transcript is not persisted');await snap('editable-transcript');
 await input.fill('Where are the drawing tools?');await page.getByRole('button',{name:'Send',exact:true}).click();await page.getByRole('article',{name:'Assistant reply',exact:true}).waitFor();equal(guidance,1,'only ordinary explicit Send invokes guidance');await page.waitForTimeout(500);
 await page.getByRole('button',{name:'New Chat',exact:true}).click();await input.fill('Typed while transcribing.');mode='hold';await record();await page.getByRole('button',{name:'Stop dictation'}).click();await page.getByText('Transcribing… You can keep typing or cancel.').waitFor();await input.fill('Still editable.');await page.getByRole('button',{name:'Cancel dictation'}).click();release();await page.waitForTimeout(350);equal(await input.inputValue(),'Still editable.','Cancel during transcription suppresses late output and keeps typing');await cleanup('transcription Cancel cleans all capture resources');mode='success';
 await page.evaluate(()=>window.__p5.permission='hold');await mic.click();await page.getByRole('button',{name:'Cancel dictation'}).click();await page.evaluate(()=>window.__p5.release?.());await page.waitForTimeout(300);await cleanup('late permission after Cancel stops newly delivered tracks');await page.evaluate(()=>window.__p5.permission='allow');
 await page.evaluate(()=>window.__p5.permission='hold');await mic.click();await page.evaluate(()=>window.__p5.permissions.at(-1)?.());await waitIdle();check((await page.locator('body').innerText()).includes('timed out'),'pending permission timeout is recoverable');await page.evaluate(()=>window.__p5.release?.());await page.waitForTimeout(200);await cleanup('permission timeout releases any late stream');await page.evaluate(()=>window.__p5.permission='allow');
 for(const permission of ['denied','missing','busy']){await page.evaluate(p=>window.__p5.permission=p,permission);await mic.click();await waitIdle();await input.fill(`Typing after ${permission}`);check((await page.locator('body').innerText()).includes(permission==='denied'?'Microphone access was denied':'microphone is unavailable'),`${permission} recoverable message`);await cleanup(`${permission} cleanup`);}await page.evaluate(()=>window.__p5.permission='allow');
 for(const failure of ['failure','empty','oversize']){mode=failure;await record();await page.getByRole('button',{name:'Stop dictation'}).click();await waitIdle();check((await page.locator('body').innerText()).includes(failure==='failure'?'Transcription could not finish':failure==='empty'?'No speech was captured':'transcript could not be verified'),`${failure} output rejected honestly`);await cleanup(`${failure} cleanup`);}mode='success';
 await record();await page.evaluate(()=>window.__p5.limits.at(-1)?.());await waitIdle();check((await page.locator('body').innerText()).includes('reached its limit'),'120000 ms recording limit discards without upload');await cleanup('time limit cleanup');
 mode='hold';await record();await page.getByRole('button',{name:'Stop dictation'}).click();await page.getByText('Transcribing… You can keep typing or cancel.').waitFor();await page.evaluate(()=>window.__p5.deadlines.at(-1)?.());release();await waitIdle();check((await page.locator('body').innerText()).includes('timed out'),'45000 ms client timeout ignores late completion');mode='success';
 await record();await page.evaluate(()=>window.__p5.tracks.at(-1)?.dispatchEvent(new Event('ended')));await waitIdle();await cleanup('device unplug cancels and releases capture');
 await record();await page.getByRole('button',{name:'New Chat',exact:true}).click();await waitIdle();await cleanup('blank New Chat cancels capture without session changes');
 await record();await page.getByRole('link',{name:'Back to Home'}).click();await page.getByRole('button',{name:/AI Assistant/}).waitFor();await cleanup('route exit unmount releases capture');await page.goto(`${origin}/assistant`);
 await context.setOffline(true);await mic.click();await waitIdle();check((await page.locator('body').innerText()).includes('offline'),'offline microphone is recoverable before permission');await context.setOffline(false);
 await page.evaluate(()=>window.__p5.permission='silent');const beforeSilence=transcriptions;await record();await page.getByRole('button',{name:'Stop dictation'}).click();await waitIdle();equal(transcriptions,beforeSilence,'actual silent samples rejected before provider');await cleanup('silence cleanup');await page.evaluate(()=>window.__p5.permission='allow');
 await input.fill('Original.');mode='hold';await record();const beforeRace=transcriptions;await page.getByRole('button',{name:'Stop dictation'}).evaluate(el=>{(el as HTMLButtonElement).click();document.querySelector<HTMLButtonElement>('[aria-label="Cancel dictation"]')?.click();});await waitIdle();release();await page.waitForTimeout(150);equal(await input.inputValue(),'Original.','same-task Stop/Cancel race never inserts');check(transcriptions<=beforeRace+1,'Stop/Cancel race dispatches at most once');mode='success';await cleanup('Stop/Cancel race cleanup');
 await input.fill('a'.repeat(11999));await record();await page.getByRole('button',{name:'Stop dictation'}).click();await waitIdle();equal((await input.inputValue()).length,11999,'oversized draft append preserves exact existing draft');check((await page.locator('body').innerText()).includes('enough room'),'full draft has recoverable message');await input.fill('');
 mode='hold';await record();await page.getByRole('button',{name:'Stop dictation'}).click();await page.getByText('Transcribing… You can keep typing or cancel.').waitFor();await page.getByRole('button',{name:'Open chat: Drawing tools',exact:true}).click();release();await page.waitForTimeout(200);equal(await input.inputValue(),'','chat switch cannot insert into another draft');mode='success';await page.getByRole('button',{name:'New Chat',exact:true}).click();
 const rapidBefore=transcriptions;await record();await page.getByRole('button',{name:'Stop dictation'}).evaluate(el=>{(el as HTMLButtonElement).click();(el as HTMLButtonElement).click();});await waitIdle();equal(transcriptions,rapidBefore+1,'double Stop issues exactly one transcription');await cleanup('double Stop cleanup');
 for(const [name,width,height,reduced,forced] of [['compact',390,844,false,false],['narrow',320,740,false,false],['zoom',720,450,false,false],['reduced',1280,900,true,false],['forced',1280,900,false,true]] as const){await page.setViewportSize({width,height});await page.emulateMedia({reducedMotion:reduced?'reduce':'no-preference',forcedColors:forced?'active':'none'});await record();equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${name} no horizontal overflow`);const stop=page.getByRole('button',{name:'Stop dictation'});await stop.focus();check(await stop.evaluate(el=>el===document.activeElement),`${name} Stop keyboard accessible`);await snap(name);await page.addScriptTag({path:'node_modules/axe-core/axe.min.js'});const violations=await page.evaluate(async()=>{const r=await (window as unknown as {axe:{run:(selector:string)=>Promise<{violations:{impact:string}[]}>}}).axe.run('[data-assistant-screen]');return r.violations.filter(v=>v.impact==='serious'||v.impact==='critical');});equal(violations,[],`${name} Axe has zero serious/critical findings`);accessibility.push({name,violations});await page.getByRole('button',{name:'Cancel dictation'}).click();await waitIdle();await cleanup(`${name} cleanup`);}
 equal(await page.evaluate(()=>localStorage.getItem('phase5-protected-project-sentinel')),'unchanged','protected storage sentinel unchanged');equal(errors,[],'zero browser errors or external/unrelated API requests');
 writeFileSync(`${output}/result.json`,JSON.stringify({status:'PASS',assertions,accessibility,errors,requests,screenshots,storageDigests,transcriptions,guidance,maxRecorded,performance:{sampleInspectionMs,stopCompletionMs,actualAnalyserReads:samples.calls,actualPeak:samples.peak},realProviderCalls:0,paidCalls:0,rawAudioWritten:false,traceAndHarDisabled:true},null,2));console.log(JSON.stringify({status:'PASS',assertions:assertions.length,transcriptions,guidance}));await context.close();
}finally{await browser.close();}
