import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { execFileSync, spawnSync } from 'node:child_process';
import { lstatSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { DICTATION_LIMITS } from '../../../src/lib/assistant/assistantDictationContract.ts';
const root='output/spec-0012/phase-5',base='3676cfabba28554c4e5106a7cfb8822ac7c8c456';
const paths=[
'app/api/diamond-assistant-transcription/route.ts','public/assistant/dictation-worklet.js',
'src/components/assistant/AssistantComposer.tsx','src/components/assistant/DiamondAssistantScreen.tsx','src/components/assistant/diamondAssistant.module.css',
'src/lib/assistant/assistantDictationCapture.ts','src/lib/assistant/assistantDictationContract.ts','src/lib/assistant/assistantTranscriptionService.ts',
...['browser.ts','build.ts','contract.json','oracle.ts','regressions.ts','routeProof.ts','proof.ts','validate.ts'].map(name=>`scripts/spec0012-assistant/phase5/${name}`)
].sort();
const git=(...args:string[])=>execFileSync('git',args,{encoding:'utf8'}).trim();const sha=(b:string|Buffer)=>createHash('sha256').update(b).digest('hex');const json=(p:string)=>JSON.parse(readFileSync(p,'utf8'));const bind=(path:string)=>{const b=readFileSync(path);return {path,bytes:b.length,sha256:sha(b)};};
assert.equal(git('rev-parse','HEAD'),base);assert.equal(git('diff','--cached','--name-only'),'');const dirty=execFileSync('git',['status','--porcelain','--untracked-files=all'],{encoding:'utf8'}).split('\n').filter(Boolean).map(s=>s.slice(3)).sort();assert.deepEqual(dirty,paths);
mkdirSync(`${root}/receipts`,{recursive:true});
for(const [name,command,args] of [
 ['typescript',process.execPath,['node_modules/typescript/bin/tsc','--noEmit','--incremental','false']],
 ['focused-lint',process.execPath,['node_modules/eslint/bin/eslint.js',...paths.filter(p=>/\.(ts|tsx|js)$/.test(p))]],
 ['diff-check','git',['diff','--check']],
] as [string,string,string[]][]){const r=spawnSync(command,args,{encoding:'utf8',maxBuffer:32*1024*1024});writeFileSync(`${root}/receipts/${name}.json`,JSON.stringify({name,command:[command,...args],exitCode:r.status,stdout:r.stdout,stderr:r.stderr},null,2));assert.equal(r.status,0,r.stdout+r.stderr);}
const lint=spawnSync(process.execPath,['node_modules/eslint/bin/eslint.js','.','--ignore-pattern','output/**','--format','json'],{encoding:'utf8',maxBuffer:64*1024*1024});const findings=JSON.parse(lint.stdout) as {filePath:string;errorCount:number;warningCount:number;messages:unknown[]}[];let errors=0,warnings=0;for(const f of findings){errors+=f.errorCount;warnings+=f.warningCount;if(f.messages.length){const path=f.filePath.slice(process.cwd().length+1);assert.ok(!paths.includes(path),`new lint finding ${path}`);assert.equal(readFileSync(path,'utf8'),execFileSync('git',['show',`${base}:${path}`],{encoding:'utf8'}));}}writeFileSync(`${root}/receipts/full-lint.json`,JSON.stringify({status:'INHERITED_BASELINE',scope:'repository; ignored output/** proof artifacts excluded',errors,warnings,findings},null,2));
const oracle=json(`${root}/oracle/result.json`),browser=json(`${root}/browser/result.json`),regressions=json(`${root}/regressions/result.json`),build=json(`${root}/build/result.json`),route=json(`${root}/route/result.json`);
for(const r of [oracle,browser,regressions,build,route])assert.equal(r.status,'PASS');assert.equal(browser.realProviderCalls,0);assert.deepEqual(browser.errors,[]);assert.ok(browser.assertions.length>=71);assert.equal(browser.accessibility.length,5);assert.ok(browser.accessibility.every((a:{violations:unknown[]})=>!a.violations.length));assert.equal(regressions.receipts.length,5);
const audioRoots=['src/lib/assistant/assistantDictationCapture.ts','src/lib/assistant/assistantDictationContract.ts','src/lib/assistant/assistantTranscriptionService.ts','public/assistant/dictation-worklet.js'];for(const path of audioRoots){const s=readFileSync(path,'utf8');assert.ok(!/localStorage|indexedDB|writeFile|console\.|createObjectURL|\/api\/ai|assistantStorage|assistantProvider|assistantJobService|projectRepository/.test(s),path);}
const walk=(dir:string):string[]=>readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(`${dir}/${e.name}`):[`${dir}/${e.name}`]);
const rawAudioFiles=walk(root).filter(path=>/\.(wav|webm|mp3|m4a|ogg|pcm)$/i.test(path)||readFileSync(path).subarray(0,4).equals(Buffer.from('RIFF')));assert.deepEqual(rawAudioFiles,[]);
const pid=Number(execFileSync('lsof',['-nP','-iTCP:58070','-sTCP:LISTEN','-t'],{encoding:'utf8'}).trim());assert.ok(pid>0);const cwd=execFileSync('lsof',['-a','-p',String(pid),'-d','cwd','-Fn'],{encoding:'utf8'}).split('\n').find(s=>s.startsWith('n'))?.slice(1);assert.equal(cwd,process.cwd());const ports=[...new Set([...execFileSync('lsof',['-nP','-iTCP','-sTCP:LISTEN'],{encoding:'utf8'}).matchAll(/:(58\d{3}) \(LISTEN\)/g)].map(m=>Number(m[1])))].sort();assert.deepEqual(ports,[58070]);
const health=await fetch('http://127.0.0.1:58070/assistant');assert.equal(health.status,200);
writeFileSync(`${root}/review-server.json`,JSON.stringify({url:'http://127.0.0.1:58070/assistant',port:58070,pid,cwd,mode:'production',health:200,reviewPorts:ports,credentialSymlink:lstatSync('.env.local').isSymbolicLink(),credentialIgnored:git('check-ignore','.env.local')==='.env.local',credentialTracked:git('ls-files','.env.local')!=='',credentialContentsReadOrPrinted:false},null,2));
writeFileSync(`${root}/boundary.json`,JSON.stringify({status:'PASS',audioRoots,rawAudioFiles,rawAudioWritten:false,objectUrlsCreated:0,projectMutation:false,protectedSourcesEqual:regressions.protectedSourceBytesEqual,existingRevealCssEqual:regressions.existingRevealCssEqual,allOtherTrackedPathsEqual:true},null,2));
const sources=paths.map(bind);const evidence=walk(root).filter(p=>!/(proof-manifest|validation)\.json$/.test(p)).sort().map(bind);
const manifest={schema:'spec0012-phase5-proof/v1',status:'PASS',base,head:git('rev-parse','HEAD'),branch:git('branch','--show-current')||'(detached)',worktree:process.cwd(),role:'Spec Executor',indexEmpty:true,dirtyPathAllowlist:paths,spec:bind('docs/specs/0012-diamond-animator-guidance-assistant.md'),authority:json('scripts/spec0012-assistant/phase5/contract.json').authority,limits:DICTATION_LIMITS,sources,sourceDigest:sha(JSON.stringify(sources)),evidence,proof:{oracleAssertions:oracle.assertions.length,browserAssertions:browser.assertions.length,regressionGroups:regressions.receipts.length,accessibility:browser.accessibility,performance:browser.performance,storageDigests:browser.storageDigests,requestLedger:browser.requests,transcriptionDoubles:browser.transcriptions,guidanceDoubles:browser.guidance,realProviderCalls:0,paidCalls:0,automatedSpendUsd:0,rawAudioWritten:false,traceAndHarDisabled:true,focusedBuild:build.focused.status,fullBuild:build.full.status,fullLint:{errors,warnings,changedFindings:0}},review:json(`${root}/review-server.json`),humanAcceptance:'pending Arthur',controlPlaneUpdated:false,gitPublication:false,staged:false,committed:false,merged:false,pushed:false,deployed:false,laterPhaseStarted:false,cleanup:'Keep this exact review server and worktree for Arthur/PM review; CPA transfer only after stopped executor and acceptance; no cleanup of other worktrees.',unproven:['physical microphone and physical devices','non-Chromium browsers','live provider account access, transcript accuracy and provider latency','provider-side RAM erasure; only documented retention terms and local lifecycle are claimed','provider model echo is optional in documented transcription JSON; fixed requested model and mismatched-echo rejection are proven']};
writeFileSync(`${root}/proof-manifest.json`,JSON.stringify(manifest,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({status:'SEALED',manifest:bind(`${root}/proof-manifest.json`),sourceDigest:manifest.sourceDigest,sources:sources.length,evidence:evidence.length,review:manifest.review.url}));
