import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const base='3676cfabba28554c4e5106a7cfb8822ac7c8c456';const output=resolve('output/spec-0012/phase-5/regressions');mkdirSync(output,{recursive:true});
const receipts:Record<string,unknown>[]=[];const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
function run(name:string,path:string,adapt:(s:string)=>string=s=>s){const source=readFileSync(path,'utf8');const adapted=(name==='inherited-oracles'||name==='protected-browser')?adapt(source):adapt(source).replaceAll('"../../src/',`"${resolve('src')}/`).replaceAll('"./phase2Fixtures.ts"',`"${resolve('scripts/spec0012-assistant/phase2Fixtures.ts')}"`).replaceAll('"./phase4Fixtures.ts"',`"${resolve('scripts/spec0012-assistant/phase4Fixtures.ts')}"`);const target=resolve(output,`${name}.ts`);writeFileSync(target,adapted);const result=spawnSync(process.execPath,['--experimental-strip-types',target],{encoding:'utf8',maxBuffer:64*1024*1024,env:{...process.env,OPENAI_API_KEY:'',SPEC0012_PHASE4_ORIGIN:'http://127.0.0.1:58070',SPEC0012_REVEAL_ORIGIN:'http://127.0.0.1:58070'}});writeFileSync(`${output}/${name}.log`,result.stdout+'\n'+result.stderr);receipts.push({name,path,sourceSha256:sha(source),adaptedSha256:sha(adapted),exitCode:result.status});assert.equal(result.status,0,`${name}: ${result.stdout.slice(-2000)} ${result.stderr.slice(-4000)}`);console.log(`PASS ${name}`);}
run('phase4-oracle','scripts/spec0012-assistant/phase4Oracle.ts',s=>s.replaceAll('output/spec-0012/phase-4/oracle','output/spec-0012/phase-5/regressions/phase4-oracle'));
run('inherited-oracles','scripts/spec0012-assistant/phase4Regressions.ts',s=>s.replaceAll('741ee803f9e0bd72f7c64174a77e52a6ac3a7b17',base).replaceAll('output/spec-0012/phase-4/regressions','output/spec-0012/phase-5/regressions/inherited-oracles'));
if(!process.argv.includes('--oracles-only')){
 run('phase4-browser','scripts/spec0012-assistant/phase4BrowserProof.ts',s=>s.replace('ASSISTANT_LIMITS.deadlineMs, 250','ASSISTANT_LIMITS.deadlineMs, 3000').replaceAll('output/spec-0012/phase-4/browser','output/spec-0012/phase-5/regressions/phase4-browser'));
 run('reply-reveal','scripts/spec0012-assistant/phase4ReplyRevealBrowserProof.ts',s=>s.replaceAll('output/spec-0012/phase-4-reply-reveal/browser','output/spec-0012/phase-5/regressions/reply-reveal'));
 run('protected-browser','scripts/spec0012-assistant/phase4ReplyRevealRegressions.ts',s=>s.replaceAll('741ee803f9e0bd72f7c64174a77e52a6ac3a7b17',base).replaceAll('output/spec-0012/phase-4-reply-reveal/regressions','output/spec-0012/phase-5/regressions/protected-browser'));
}
const changed=execFileSync('git',['diff','--name-only',base],{encoding:'utf8'}).trim().split('\n').filter(Boolean).sort();assert.deepEqual(changed,['src/components/assistant/AssistantComposer.tsx','src/components/assistant/DiamondAssistantScreen.tsx','src/components/assistant/diamondAssistant.module.css']);
const protectedFiles=['src/lib/assistant/assistantContracts.ts','src/lib/assistant/assistantJobService.ts','src/lib/assistant/assistantProvider.ts','src/lib/assistant/assistantSearchPolicy.ts','src/lib/assistant/assistantStorage.ts','src/components/assistant/useAssistantSessions.ts','src/components/assistant/AssistantConversation.tsx','src/components/assistant/AssistantText.tsx','src/components/assistant/AssistantSessionSidebar.tsx'];
for(const path of protectedFiles)assert.equal(readFileSync(path,'utf8'),execFileSync('git',['show',`${base}:${path}`],{encoding:'utf8'}));
const oldCss=execFileSync('git',['show',`${base}:src/components/assistant/diamondAssistant.module.css`],{encoding:'utf8'});const css=readFileSync('src/components/assistant/diamondAssistant.module.css','utf8');assert.equal(css.split('/* Assistant-only dictation:')[0].trim(),oldCss.replace('color: #95aecb; cursor: not-allowed;','color: #b9d9ff; cursor: pointer;').trim());
writeFileSync(`${output}/result.json`,JSON.stringify({status:'PASS',receipts,base,changed,protectedFiles,protectedSourceBytesEqual:true,existingRevealCssEqual:true,realProviderCalls:0,paidCalls:0},null,2));
