import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
const root='output/spec-0012/phase-5',base='3676cfabba28554c4e5106a7cfb8822ac7c8c456';
const allowed=[
'app/api/diamond-assistant-transcription/route.ts','public/assistant/dictation-worklet.js',
'src/components/assistant/AssistantComposer.tsx','src/components/assistant/DiamondAssistantScreen.tsx','src/components/assistant/diamondAssistant.module.css',
'src/lib/assistant/assistantDictationCapture.ts','src/lib/assistant/assistantDictationContract.ts','src/lib/assistant/assistantTranscriptionService.ts',
...['browser.ts','build.ts','contract.json','oracle.ts','regressions.ts','routeProof.ts','proof.ts','validate.ts'].map(n=>`scripts/spec0012-assistant/phase5/${n}`)].sort();
const git=(...args:string[])=>execFileSync('git',args,{encoding:'utf8'}).trim();const sha=(b:string|Buffer)=>createHash('sha256').update(b).digest('hex');const json=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
type Binding={path:string;bytes:number;sha256:string};
const walk=(dir:string):string[]=>readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(`${dir}/${e.name}`):[`${dir}/${e.name}`]);
const bind=(b:Binding)=>{assert.ok(!b.path.startsWith('/')&&!b.path.includes('..')&&!b.path.includes('.env'));const bytes=readFileSync(b.path);assert.equal(bytes.length,b.bytes,b.path);assert.equal(sha(bytes),b.sha256,b.path);};
const expectedLimits={seconds:120,bytes:20971520,timeoutMs:45000,permissionMs:30000,outputChars:6000,outputBytes:12000,responseBytes:64000,active:2,identities:500,usdPerMinute:.0045,maxUsd:.009};
const manifest=json(`${root}/proof-manifest.json`);
function validate(m:typeof manifest){
 assert.equal(m.schema,'spec0012-phase5-proof/v1');assert.equal(m.status,'PASS');assert.equal(m.base,base);assert.equal(m.head,base);assert.equal(m.worktree,process.cwd());assert.equal(m.branch,git('branch','--show-current')||'(detached)');assert.equal(m.role,'Spec Executor');assert.equal(m.indexEmpty,true);assert.equal(git('rev-parse','HEAD'),base);assert.equal(git('diff','--cached','--name-only'),'');
 const actual=execFileSync('git',['status','--porcelain','--untracked-files=all'],{encoding:'utf8'}).split('\n').filter(Boolean).map(s=>s.slice(3)).sort();assert.deepEqual(actual,allowed);assert.deepEqual(m.dirtyPathAllowlist,allowed);assert.deepEqual(m.sources.map((b:Binding)=>b.path),allowed);m.sources.forEach(bind);assert.equal(m.sourceDigest,sha(JSON.stringify(m.sources)));assert.deepEqual(m.limits,expectedLimits);
 assert.equal(m.spec.path,'docs/specs/0012-diamond-animator-guidance-assistant.md');bind(m.spec);assert.equal(m.authority,json('scripts/spec0012-assistant/phase5/contract.json').authority);
 const files=walk(root).filter(p=>!/(proof-manifest|validation)\.json$/.test(p)).sort();assert.deepEqual(m.evidence.map((b:Binding)=>b.path),files);m.evidence.forEach(bind);
 const o=json(`${root}/oracle/result.json`),b=json(`${root}/browser/result.json`),r=json(`${root}/regressions/result.json`),build=json(`${root}/build/result.json`),route=json(`${root}/route/result.json`),boundary=json(`${root}/boundary.json`);
 for(const result of [o,b,r,build,route,boundary])assert.equal(result.status,'PASS');assert.equal(o.assertions.length,33);assert.ok(b.assertions.length>=71);assert.equal(r.receipts.length,5);assert.ok(r.receipts.every((v:{exitCode:number})=>v.exitCode===0));assert.equal(route.receipts.length,4);
 for(const key of ['typescript','focused-lint','diff-check'])assert.equal(json(`${root}/receipts/${key}.json`).exitCode,0);
 assert.equal(m.proof.oracleAssertions,o.assertions.length);assert.equal(m.proof.browserAssertions,b.assertions.length);assert.equal(m.proof.regressionGroups,5);assert.deepEqual(m.proof.requestLedger,b.requests);assert.equal(m.proof.transcriptionDoubles,b.transcriptions);assert.equal(m.proof.guidanceDoubles,b.guidance);assert.equal(b.guidance,1);assert.equal(b.transcriptions,9);
 for(const k of ['realProviderCalls','paidCalls','automatedSpendUsd'])assert.equal(m.proof[k],0);assert.equal(m.proof.rawAudioWritten,false);assert.equal(m.proof.traceAndHarDisabled,true);assert.equal(b.rawAudioWritten,false);assert.deepEqual(b.errors,[]);assert.deepEqual(boundary.rawAudioFiles,[]);assert.equal(boundary.objectUrlsCreated,0);assert.equal(boundary.projectMutation,false);assert.equal(boundary.protectedSourcesEqual,true);assert.equal(boundary.existingRevealCssEqual,true);
 assert.deepEqual(m.proof.accessibility,b.accessibility);assert.equal(b.accessibility.length,5);for(const p of b.accessibility)assert.deepEqual(p.violations,[]);assert.deepEqual(m.proof.performance,b.performance);assert.ok(b.performance.actualAnalyserReads>10);assert.ok(b.performance.actualPeak>0);assert.ok(b.performance.stopCompletionMs<5000);assert.deepEqual(m.proof.storageDigests,b.storageDigests);assert.equal(b.storageDigests.before,b.storageDigests.afterCancel);assert.equal(b.storageDigests.before,b.storageDigests.afterTranscript);
 assert.equal(m.proof.focusedBuild,'PASS');assert.equal(build.focused.status,'PASS');assert.equal(m.proof.fullBuild,'INHERITED_BASELINE_FAILURE');assert.equal(build.full.path,'app/dev/ai-costs/lifetime/page.tsx');assert.equal(build.full.sourceSha256,sha(execFileSync('git',['show',`${base}:${build.full.path}`])));assert.equal(m.proof.fullLint.changedFindings,0);const lint=json(`${root}/receipts/full-lint.json`);assert.equal(m.proof.fullLint.errors,lint.errors);assert.equal(m.proof.fullLint.warnings,lint.warnings);
 assert.equal(m.humanAcceptance,'pending Arthur');for(const flag of ['controlPlaneUpdated','gitPublication','staged','committed','merged','pushed','deployed','laterPhaseStarted'])assert.equal(m[flag],false);
 assert.deepEqual(m.review,json(`${root}/review-server.json`));assert.equal(m.review.url,'http://127.0.0.1:58070/assistant');assert.equal(m.review.cwd,process.cwd());assert.equal(m.review.mode,'production');assert.deepEqual(m.review.reviewPorts,[58070]);assert.equal(m.review.credentialSymlink,true);assert.equal(m.review.credentialIgnored,true);assert.equal(m.review.credentialTracked,false);assert.equal(m.review.credentialContentsReadOrPrinted,false);assert.ok(m.cleanup.includes('Keep this exact review server'));assert.ok(m.unproven.includes('physical microphone and physical devices'));
}
validate(manifest);
const mutations:[string,(m:typeof manifest)=>void][]=[
 ['base',m=>m.base='wrong'],['head',m=>m.head='wrong'],['branch',m=>m.branch='wrong'],['worktree',m=>m.worktree='wrong'],['index',m=>m.indexEmpty=false],['allowlist',m=>m.dirtyPathAllowlist.pop()],['sources',m=>m.sources.pop()],['source hash',m=>m.sources[0].sha256='0'.repeat(64)],['source size',m=>m.sources[0].bytes++],['source digest',m=>m.sourceDigest='wrong'],['evidence path',m=>m.evidence.pop()],['artifact hash',m=>m.evidence[0].sha256='wrong'],['spec',m=>m.spec.sha256='wrong'],['audio seconds',m=>m.limits.seconds=121],['audio bytes',m=>m.limits.bytes++],['timeout',m=>m.limits.timeoutMs++],['cost',m=>m.limits.maxUsd=1],['request ledger',m=>m.proof.requestLedger.pop()],['request count',m=>m.proof.transcriptionDoubles++],['paid calls',m=>m.proof.paidCalls=1],['raw retention',m=>m.proof.rawAudioWritten=true],['storage digest',m=>m.proof.storageDigests.before='bad'],['accessibility',m=>m.proof.accessibility[0].violations.push({impact:'critical'})],['performance',m=>m.proof.performance.stopCompletionMs=9000],['build',m=>m.proof.focusedBuild='FAIL'],['acceptance',m=>m.humanAcceptance='accepted'],['control plane',m=>m.controlPlaneUpdated=true],['publication',m=>m.gitPublication=true],['stage',m=>m.staged=true],['port',m=>m.review.port=3000],['credential exposure',m=>m.review.credentialTracked=true],['later phase',m=>m.laterPhaseStarted=true]
];
for(const [name,mutate] of mutations){const changed=structuredClone(manifest);mutate(changed);assert.throws(()=>validate(changed),name);}
const health=await fetch(manifest.review.url);assert.equal(health.status,200);assert.equal(Number(execFileSync('lsof',['-nP','-iTCP:58070','-sTCP:LISTEN','-t'],{encoding:'utf8'}).trim()),manifest.review.pid);
const result={status:'VALID',manifestSha256:sha(readFileSync(`${root}/proof-manifest.json`)),sourceDigest:manifest.sourceDigest,sources:allowed.length,evidence:manifest.evidence.length,negativeCases:mutations.map(([name])=>name),indexEmpty:true};writeFileSync(`${root}/validation.json`,JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result));
