import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync, lstatSync } from "node:fs";
import { resolve, relative } from "node:path";
import { execFileSync } from "node:child_process";
type Binding={path:string;byteLength:number;sha256:string};
type Manifest={kind:string;version:number;phase:number;status:string;baseSha:string;headSha:string;worktree:string;branch:string;indexEmpty:boolean;pathCeiling:number;exactDirtyPaths:string[];sourceBindings:Binding[];frozenPhase1:Array<{path:string;sha256:string}>;receipts:Array<Binding&{id:string}>;artifacts:Binding[];evidence:Record<string,unknown>;review:Record<string,unknown>;createdAt:string};
const base="804ff39dc73c88d4799570cce2ef18987745a0be",out="output/spec-0006/phase-2";
const expectedPaths=["app/page.tsx","src/components/open-project/OpenProjectBrowser.tsx","src/components/workspace/AnimationWorkspace.tsx","src/components/workspace/AnimationWorkspace.module.css","src/lib/animation/unifiedProjectCollection.ts","src/lib/animation/unifiedProjectSourceReader.ts","src/lib/animation/unifiedWorkspaceBootstrap.ts","src/components/workspace/DrawingWorkspace.tsx","src/lib/drawingProjectStorage.ts","scripts/fixtures/spec0006-unified/v1/phase2-cases.json","scripts/spec0006-unified/phase2FixtureFactory.ts","scripts/spec0006-unified/validatePhase2Navigation.ts","scripts/spec0006-unified/phase2BrowserProof.ts","scripts/spec0006-unified/recordPhase2Proof.ts","scripts/spec0006-unified/validatePhase2Proof.ts"];
const expectedReceipts=["navigation","phase1-migration","typescript","focused-lint","full-lint","drawing-v1","drawing-v2-contract","drawing-v2-repository","stick-history-storage","stick-timeline","stick-ai-adapter","stick-transaction","stick-motion","stick-timing","stick-safety","drawing-memory","drawing-preferences","drawing-route-isolation","diff-check"];
const sha=(bytes:Uint8Array)=>createHash("sha256").update(bytes).digest("hex");
const file=(binding:Binding)=>{assert.deepEqual(Object.keys(binding).sort(),["byteLength","path","sha256"]);assert.ok(!relative(process.cwd(),resolve(binding.path)).startsWith(".."));assert.equal(lstatSync(binding.path).isSymbolicLink(),false);const bytes=readFileSync(binding.path);assert.equal(bytes.length,binding.byteLength);assert.equal(sha(bytes),binding.sha256);};
const verify=(m:Manifest)=>{
  assert.deepEqual(Object.keys(m).sort(),["kind","version","phase","status","baseSha","headSha","worktree","branch","indexEmpty","pathCeiling","exactDirtyPaths","sourceBindings","frozenPhase1","receipts","artifacts","evidence","review","createdAt"].sort());
  assert.equal(m.kind,"spec0006-phase2-technical-proof");assert.equal(m.version,1);assert.equal(m.phase,2);assert.equal(m.status,"PASS");assert.equal(m.baseSha,base);assert.equal(m.headSha,base);assert.equal(m.worktree,process.cwd());assert.equal(m.branch,"detached-HEAD");assert.equal(m.indexEmpty,true);assert.equal(m.pathCeiling,16);assert.deepEqual(m.exactDirtyPaths,expectedPaths);
  assert.deepEqual(m.sourceBindings.map(b=>b.path),expectedPaths);m.sourceBindings.forEach(file);
  assert.deepEqual(m.frozenPhase1,[{path:"src/lib/animation/unifiedAnimationContract.ts",sha256:"249cfd4640b129927fa7206cf3c8b17bb0c98f4ecf46af0adb2d33125fc9168d"},{path:"src/lib/animation/unifiedAnimationMigration.ts",sha256:"093ccf4127bfe66adbf3ae6819c5118389e7e3a70efa53469eb9551065e6c28e"}]);for(const frozen of m.frozenPhase1)assert.equal(sha(readFileSync(frozen.path)),frozen.sha256);
  assert.deepEqual(m.receipts.map(r=>r.id),expectedReceipts);for(const {id,...binding} of m.receipts){assert.equal(binding.path,`${out}/receipts/${id}.json`);file(binding);const receipt=JSON.parse(readFileSync(binding.path,"utf8"));assert.equal(receipt.id,id);assert.equal(receipt.exitCode,["full-lint","drawing-route-isolation"].includes(id)?1:0);assert.equal(receipt.expected,receipt.exitCode);assert.ok(Array.isArray(receipt.command)&&receipt.command.length>=2);}
  assert.equal(new Set(m.artifacts.map(a=>a.path)).size,m.artifacts.length);m.artifacts.forEach(file);
  const bound=new Set(m.artifacts.map(a=>a.path));for(const path of ["boot/plan.json","boot/base-lint.json","boot/browser.json","lint-comparison.json","browser/result.json","production-build.json","review-server-identity.json","server-network.snapshot.jsonl","route-current-status.ts","route-current-status-proof.json","tsconfig.source.json","generated-type-baseline.json"])assert.ok(bound.has(`${out}/${path}`));
  const browser=JSON.parse(readFileSync(`${out}/browser/result.json`,"utf8"));assert.equal(browser.status,"PASS");assert.ok(browser.operations.length>=40);assert.equal(browser.screenshots.length,13);for(const path of [...browser.screenshots,...browser.accessibility])assert.ok(bound.has(`${out}/browser/${path}`));
  for(const tag of ["desktop","compact"])for(const name of ["tutorials-back-focus","open-during-new-bootstrap","new-direct-title","workspace-visual-preservation","drawing-tools-history","open-back-focus","cancel-pending-open","combined-collection","invalid-disabled","open-Drawing study (V1)","open-Drawing study (V2)","open-Stick study (V1)","open-Stick study (V2)","source-change-rejection","missing-asset-rejection","double-open-single-editor","inherited-responsive-layout","refresh-home"])assert.ok(browser.operations.includes(`${tag}:${name}`));
  assert.ok(browser.operations.includes("desktop:stick-edit-history-creator"));assert.equal(browser.operations.includes("compact:stick-edit-history-creator"),false);
  for(const key of ["realApiRequests","externalRequests","sourceWrites"])assert.equal(browser[key],0);assert.deepEqual(browser.pageErrors,[]);assert.deepEqual(browser.consoleErrors,[]);assert.equal(browser.reviewOnlyProductSurface,false);assert.equal(browser.inheritedWorkspaceChrome,true);assert.equal(browser.inheritedProjectsShell,true);assert.equal(browser.forbiddenPhase2ChromeAbsent,true);assert.ok(browser.requests.every((r:{disposition:string})=>["loopback","fulfilled-availability"].includes(r.disposition)));for(const snapshot of browser.storageProof){assert.deepEqual(snapshot.before,snapshot.after);assert.ok(snapshot.writes.every((w:string)=>w==="localStorage.set:da_drawing_ai_control_preferences_v1"));}
  assert.deepEqual(m.evidence,{browserOperations:browser.operations.length,screenshots:13,sourceWrites:0,realApiRequests:0,externalRequests:0,pageErrors:0,consoleErrors:0,newOrChangedLineLintFindings:0,reviewOnlyProductSurface:false,productionRuntime:true,canonicalRepositoryImplemented:false,compatibilityEditorsMerged:false});
  assert.match(String(m.review.url),/^http:\/\/127\.0\.0\.1:(?!3000\/)\d+\/$/);assert.equal(m.review.url,browser.url);assert.deepEqual(m.review,{url:browser.url,serverPreserved:true,humanAcceptance:"pending Arthur",executorOwnership:"exclusive until this task stops",publication:"not authorized",controlPlane:"unchanged"});assert.ok(Number.isFinite(Date.parse(m.createdAt)));
  const build=JSON.parse(readFileSync(`${out}/production-build.json`,"utf8"));assert.equal(build.status,"PASS");assert.deepEqual(build.modes,["compile","generate"]);assert.ok(build.receipts.every((r:{exitCode:number})=>r.exitCode===0));
  const identity=JSON.parse(readFileSync(`${out}/review-server-identity.json`,"utf8"));assert.equal(identity.cwd,process.cwd());assert.equal(identity.url,browser.url);assert.equal(identity.httpStatus,200);assert.equal(identity.reviewCopies,1);assert.ok(identity.pid>1);
  const route=JSON.parse(readFileSync(`${out}/route-current-status-proof.json`,"utf8"));assert.equal(route.status,"PASS");assert.equal(route.inheritedValidatorStatus,"FAIL");assert.equal(route.exitCode,0);assert.equal(route.providerRequests,0);file(route.original);file(route.adjusted);route.untouchedRouteBindings.forEach(file);assert.equal(readFileSync(route.adjusted.path,"utf8"),readFileSync(route.original.path,"utf8").replaceAll('=== "completed-frames"','=== "prepared-command"'));assert.deepEqual(JSON.parse(route.stdout),{allChecksPassed:true,results:{savedProjectRejectsForeignMemory:true,unsavedProjectRejectsSavedMemory:true}});
  const generatedTypes=JSON.parse(readFileSync(`${out}/generated-type-baseline.json`,"utf8"));assert.equal(generatedTypes.status,"KNOWN-FAIL");assert.equal(generatedTypes.exitCode,2);assert.equal((generatedTypes.stdout.match(/error TS2344/g)??[]).length,2);file(generatedTypes.sourceCheck);
  const lint=JSON.parse(readFileSync(`${out}/lint-comparison.json`,"utf8"));assert.equal(lint.status,"PASS");assert.deepEqual(lint.newOrChangedLineFindings,[]);assert.equal(lint.result.errors,5);assert.ok(lint.result.warnings<=lint.base.warnings);
};
const path=process.argv.find(arg=>arg.startsWith("--manifest="))?.slice(11)??`${out}/proof-manifest.json`;
const bytes=readFileSync(path),manifest=JSON.parse(bytes.toString()) as Manifest;verify(manifest);
if(!process.argv.includes("--artifacts-only")){
  const git=(...args:string[])=>execFileSync("git",args,{encoding:"utf8"});assert.equal(git("rev-parse","HEAD").trim(),base);assert.equal(git("diff","--cached","--name-only"),"");assert.deepEqual(git("status","--porcelain=v1","--untracked-files=all").split("\n").filter(Boolean).map(line=>line.slice(3)).sort(),[...expectedPaths].sort());
}
const attacks:Array<(m:Manifest)=>void>=[m=>{m.phase=3;},m=>{m.baseSha="0".repeat(40);},m=>{m.headSha="0".repeat(40);},m=>{m.indexEmpty=false;},m=>{m.exactDirtyPaths.pop();},m=>{m.sourceBindings[0].sha256="0".repeat(64);},m=>{m.sourceBindings[0].byteLength++;},m=>{m.frozenPhase1[0].sha256="0".repeat(64);},m=>{m.receipts.pop();},m=>{m.artifacts.pop();},m=>{m.evidence.sourceWrites=1;},m=>{m.evidence.productionRuntime=false;},m=>{m.review.url="http://127.0.0.1:3000/";},m=>{m.review.publication="authorized";},m=>{m.review.serverPreserved=false;},m=>{m.evidence.canonicalRepositoryImplemented=true;},m=>{m.pathCeiling=99;},m=>{m.createdAt="invalid";}];
for(const mutate of attacks){const candidate=structuredClone(manifest);mutate(candidate);assert.throws(()=>verify(candidate));}
console.log(JSON.stringify({status:"PASS",manifest:path,byteLength:bytes.length,sha256:sha(bytes),paths:expectedPaths.length,receipts:expectedReceipts.length,artifacts:manifest.artifacts.length,negativeManifestCases:attacks.length,indexEmpty:true},null,2));
