import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";

// This validator neither imports nor calls the recorder or renderer. It checks
// durable file bindings and independently enforces the phase's evidence gates.
type Binding={path:string;byteLength:number;sha256:string};
type Manifest={kind:string;version:number;phase:number;status:string;authorizationSha:string;runtimeBase:string;headSha:string;branch:string;worktree:string;indexEmpty:boolean;pathCeiling:number;exactDirtyPaths:string[];sourceBindings:Binding[];frozenBindings:Array<{path:string;sha256:string;bytes:number}>;receipts:Array<Binding&{id:string}>;artifacts:Binding[];evidence:Record<string,unknown>;review:{url:string;serverPreserved:boolean;humanAcceptance:string}};
const root=process.cwd(),out="output/spec-0006/phase-3",path=process.argv.find(a=>a.startsWith("--manifest="))?.slice(11)??`${out}/proof-manifest.json`;
const read=(p:string)=>JSON.parse(readFileSync(p,"utf8"));
const hash=(b:Uint8Array)=>createHash("sha256").update(b).digest("hex");
const expected=["src/lib/animation/unifiedCellResolver.ts","src/lib/animation/unifiedStageGeometry.ts","src/lib/animation/unifiedDrawingRenderAdapter.ts","src/lib/animation/unifiedStickRenderAdapter.ts","src/lib/animation/unifiedStageRenderer.ts","src/components/workspace/UnifiedAnimationStage.tsx","src/components/workspace/AnimationWorkspace.tsx","src/components/workspace/AnimationWorkspace.module.css","src/components/workspace/stickfigure/StickFigureWorkspace.tsx","src/components/workspace/stickfigure/StickFigureCanvas.tsx","scripts/fixtures/spec0006-unified/v1/phase3-render-cases.json","scripts/spec0006-unified/phase3FixtureFactory.ts","scripts/spec0006-unified/phase3RenderOracle.ts","scripts/spec0006-unified/phase3BrowserProof.ts","scripts/spec0006-unified/recordPhase3Proof.ts","scripts/spec0006-unified/validatePhase3Proof.ts"].sort();
let assertions=0;
const equal=(a:unknown,b:unknown)=>{assertions++;assert.deepEqual(a,b);};
const bound=(b:Binding)=>{assert.ok(!b.path.includes(".."));const bytes=readFileSync(b.path);equal(bytes.length,b.byteLength);equal(hash(bytes),b.sha256);};
function validate(m:Manifest,live=false){
  equal(m.kind,"spec0006-phase3-technical-proof");equal(m.version,1);equal(m.phase,3);equal(m.status,"PASS");
  equal(m.authorizationSha,"916a4d913c6fdf8340b67bcc88dcea184d67cd32");equal(m.runtimeBase,"d2096109900cc50a0a4dae2f603bd74b7b4a3427");equal(m.headSha,m.authorizationSha);equal(m.indexEmpty,true);equal(m.pathCeiling,16);equal(m.worktree,root);equal(m.branch,"detached-HEAD");equal(m.exactDirtyPaths,expected);equal(m.sourceBindings.map(b=>b.path).sort(),expected);
  for(const b of [...m.sourceBindings,...m.artifacts,...m.receipts])bound(b);
  for(const b of m.frozenBindings)bound({path:b.path,sha256:b.sha256,byteLength:b.bytes});
  const artifacts=new Set(m.artifacts.map(b=>b.path));
  for(const name of ["contracts.json","browser/result.json","production-build.json","source-copy.json","review-server-identity.json","lint-comparison.json","server-network.snapshot.jsonl","boot/plan.json","boot/fixture-freeze.json","boot/fixture-correction.json","boot/neutral-fixture-correction.json","scope-audit.json","inherited-browser/result.json","inherited-browser-receipt.json"])assert.ok(artifacts.has(`${out}/${name}`));
  equal(m.evidence.profiles,2);equal(m.evidence.externalRequests,0);equal(m.evidence.realApiRequests,0);equal(m.evidence.sourceWrites,0);equal(m.evidence.documentHistoryWritesOnRender,0);equal(m.evidence.independentPixelOracle,true);equal(m.evidence.productionBuild,true);equal(m.evidence.toolHistoryPersistenceOwnersUnchanged,true);equal(m.evidence.phase4Implemented,false);
  const contracts=read(`${out}/contracts.json`);equal(contracts.status,"PASS");assert.ok(contracts.assertions>=7000);assert.ok(contracts.randomizedLayerCases>=1024);assert.ok(contracts.maxCoordinateError<1e-5);
  const browser=read(`${out}/browser/result.json`);equal(browser.status,"PASS");equal(browser.profiles.length,2);equal(browser.errors,[]);equal(browser.externalRequests,0);equal(browser.realApiRequests,0);equal(browser.requests.filter((r:{kind:string})=>r.kind!=="loopback"),[]);
  equal(browser.neutralOwnersVerified,true);equal(browser.fixture,read("scripts/fixtures/spec0006-unified/v1/phase3-render-cases.json").frozen);assert.ok(browser.machine.cpu);equal(browser.sourceCopy.sha256,hash(readFileSync(`${out}/source-copy.json`)));
  for(const profile of browser.profiles){equal(profile.comparisons.map((c:{mismatches:number})=>c.mismatches),Array(8).fill(0));equal(profile.layout.backing,[1920,1080]);assert.ok(profile.layout.width>=260&&profile.layout.height>=146);equal(profile.layout.overflow,false);equal(profile.zeroWrites,true);equal(profile.historyStable,true);assert.ok(profile.playbackOnTime>=.95);assert.ok(profile.heap<=320*1024*1024);assert.ok(profile.accounting.peakOwnedBytes<=290838816);assert.ok(profile.accounting.decodedBytes+profile.accounting.backingBytes<=153713808);equal(profile.opens.length,5);const sorted=profile.opens.slice().sort((a:number,b:number)=>a-b),compact=profile.profile.name==="compact";assert.ok(sorted[2]<=(compact?8000:5000));assert.ok(sorted[4]<=(compact?12000:7500));}
  for(const p of browser.profiles){const compact=p.profile.name==="compact";equal(p.playbackRuns.length,5);equal(p.renderRuns.length,5);assert.ok(p.peakHeap<=512*1024*1024);for(const r of p.playbackRuns){assert.ok(r.onTime>=.95);equal(r.ticks.slice(0,49).map((t:{index:number})=>t.index),[...Array.from({length:48},(_,i)=>i),0]);assert.ok(r.ticks.every((t:{textInk:number})=>t.textInk>1000));}for(const r of p.renderRuns){equal(r.settlements.length,120);assert.ok(r.p95<=(compact?150:100));assert.ok(r.heap<=320*1024*1024);assert.ok(Math.max(0,...r.longTasks)<=(compact?750:500));assert.ok(r.longTasks.filter((n:number)=>n>100).length<=(compact?8:5));}equal(p.dprChanges.map((r:{dpr:number})=>r.dpr),[1,2,3,p.profile.dpr]);assert.ok(p.dprChanges.every((r:{backingStable:boolean})=>r.backingStable));equal(p.rapidResize,20);equal(p.zeroSizeRecovered,true);equal(p.isolated.map((r:{mismatches:number})=>r.mismatches),[0,0,0,0]);for(const name of ["missing-asset","invalid-command","adapter-throw","decode-failure","hidden-layer","locked-layer","text-only","rapid-render","shared-snapshot","dispose"])assert.ok(p.faults.some((f:{name:string})=>f.name===name));for(const key of ["oneHistoryEntry","heldOwnerEditable","independentPoseUnchanged","undoRedoExact"])equal(p.manual[key],true);assert.ok(Math.abs(p.manual.expected.x-p.manual.actual.x)<1e-7&&Math.abs(p.manual.expected.y-p.manual.actual.y)<1e-7);}
  const scope=read(`${out}/scope-audit.json`);equal(scope.status,"PASS");equal(scope.exactDirtyPaths,expected);equal(scope.aiGenerationChanges,0);equal(scope.providerApiChanges,0);equal(scope.productSeedImports,0);equal(scope.neutralFixture.identicalNeutralGeometry,true);equal(new Set(scope.neutralFixture.geometryHashes).size,1);equal(new Set(scope.neutralFixture.ownerIds).size,4);equal(scope.neutralFixture.holdCells,44);equal(scope.neutralFixture.stickInterpolation,false);equal(scope.neutralFixture.source,browser.fixture.source);assert.ok(scope.protectedBindings.length>=150);for(const b of scope.protectedBindings)bound(b);
  assert.ok(artifacts.has(`${out}/source-copy-audit.json`));const copyAudit=read(`${out}/source-copy-audit.json`);equal(copyAudit.status,"PASS");assert.ok(copyAudit.checkedFiles>=116);equal(copyAudit.productFixtureImports,0);equal(copyAudit.unchangedPackageAndConfig,true);const copy=read(`${out}/source-copy.json`);for(const i of copy.injections){equal(hash(readFileSync(i.path)),i.before);equal(hash(readFileSync(resolve(copy.copy,i.path))),i.after);}equal(hash(readFileSync(copy.seed.path)),copy.seed.sha256);
  const inherited=read(`${out}/inherited-browser/result.json`);equal(inherited.status,"PASS");equal(inherited.operations.length,40);equal(inherited.externalRequests,0);equal(inherited.realApiRequests,0);equal(inherited.sourceWrites,0);equal(inherited.pageErrors,[]);equal(inherited.consoleErrors,[]);equal(read(`${out}/inherited-browser-receipt.json`).exitCode,0);
  for(const screenshot of browser.screenshots){assert.ok(m.artifacts.some(b=>resolve(b.path)===screenshot));const signature=readFileSync(screenshot).subarray(0,8);equal([...signature],[137,80,78,71,13,10,26,10]);}
  const builds=read(`${out}/production-build.json`);equal(builds.status,"PASS");equal(builds.receipts.map((r:{exitCode:number})=>r.exitCode),[0,0]);
  const lint=read(`${out}/lint-comparison.json`);equal(lint.status,"PASS");equal(lint.base,lint.result);equal(lint.newFindings,0);
  assert.ok(m.receipts.length>=18);for(const binding of m.receipts){const r=read(binding.path);equal(r.exitCode,r.expected);}
  equal(m.review.url,"http://127.0.0.1:56463/");equal(m.review.serverPreserved,true);equal(m.review.humanAcceptance,"pending Arthur");
  // Scan changed product sources, not the intentionally instrumented ignored app.
  for(const p of expected.filter(p=>p.startsWith("src/")))assert.doesNotMatch(readFileSync(p,"utf8"),/PRIVATE REVIEW|__phase3|phase3Seed|phase3-render-cases|127\.0\.0\.1:\d|[?&]review=/);
  assert.doesNotMatch(readFileSync("scripts/spec0006-unified/phase3RenderOracle.ts","utf8"),/from ["'][^"']*(?:src\/|FixtureFactory)/);
  if(live){const git=(...args:string[])=>{const r=spawnSync("git",args,{encoding:"utf8"});equal(r.status,0);return r.stdout;};equal(git("rev-parse","HEAD").trim(),m.headSha);equal(git("diff","--cached","--name-only"),"");equal(git("status","--porcelain=v1","--untracked-files=all").split("\n").filter(Boolean).map(l=>l.slice(3)).sort(),expected);const server=read(`${out}/review-server-identity.json`);equal(server.url,m.review.url);equal(server.worktree,root);const listener=spawnSync("lsof",["-nP",`-iTCP:${server.port}`,"-sTCP:LISTEN","-t"],{encoding:"utf8"});assert.ok(listener.stdout.split(/\s+/).includes(String(server.pid)));const cwd=spawnSync("lsof",["-a","-p",String(server.pid),"-d","cwd","-Fn"],{encoding:"utf8"});assert.ok(cwd.stdout.includes(`n${server.cwd}`));}
}
const manifest=read(path) as Manifest;validate(manifest,!process.argv.includes("--offline"));
const mutations:Array<[string,(m:Manifest)=>void]>=[
  ["wrong-phase",m=>m.phase=4],["wrong-base",m=>m.runtimeBase="0".repeat(40)],["wrong-authorization",m=>m.authorizationSha="0".repeat(40)],["wrong-head",m=>m.headSha="0".repeat(40)],["nonempty-index",m=>m.indexEmpty=false],["scope-removed",m=>m.exactDirtyPaths.pop()],["scope-added",m=>m.exactDirtyPaths.push("app/page.tsx")],["source-hash",m=>m.sourceBindings[0].sha256="0".repeat(64)],["source-size",m=>m.sourceBindings[0].byteLength++],["artifact-hash",m=>m.artifacts[0].sha256="0".repeat(64)],["missing-artifacts",m=>m.artifacts=[]],["missing-receipts",m=>m.receipts=[]],["external-request",m=>m.evidence.externalRequests=1],["renderer-write",m=>m.evidence.documentHistoryWritesOnRender=1],["missing-oracle",m=>m.evidence.independentPixelOracle=false],["wrong-review",m=>m.review.url="http://127.0.0.1:3000/"],["false-human-acceptance",m=>m.review.humanAcceptance="accepted"],["phase4-leak",m=>m.evidence.phase4Implemented=true]
];
for(const [name,mutate] of mutations){const candidate=structuredClone(manifest);mutate(candidate);assert.throws(()=>validate(candidate),name);}
console.log(JSON.stringify({status:"PASS",assertions,negativeManifestCases:mutations.length,manifest:{path:resolve(path),byteLength:readFileSync(path).length,sha256:hash(readFileSync(path))}}));
