export default {
  declarationVersion: 1,
  adapterId: "phase-4-command-transaction",
  authorizationId: "phase-4/v1",
  adapterKind: "phase-4-product-ports/v1",
  executionProfile: "phase4-workspace-ports/v1",
  workspacePortBinding: "spec0001Phase4BrowserPortsV1",
  productPhaseClaimed: true,
  driverOperations: [
    {operation: "beginStickRequest", fixtureKinds: ["stick-active-request-v1"]},
    {operation: "abortStickRequest", fixtureKinds: ["stick-request-abort-v1"]},
    {operation: "previewStickCommand", fixtureKinds: ["stick-command-envelope-v1"]},
    {operation: "cancelStickPreview", fixtureKinds: ["stick-preview-cancel-v1"]},
    {operation: "applyStickCommand", fixtureKinds: ["stick-command-apply-v1"]},
    {operation: "beginApplyPublication", fixtureKinds: ["stick-command-apply-publication-plan-v1"]},
    {operation: "completeApplyPublication", fixtureKinds: ["stick-command-apply-publication-completion-v1"]},
    {operation: "redeliverStickCommand", fixtureKinds: ["stick-command-redelivery-v1"]},
    {operation: "executeInjectedTransactionFailure", fixtureKinds: ["stick-injected-transaction-failure-v1"]},
    {operation: "armNextVisibleApplyFailure", fixtureKinds: ["stick-next-visible-apply-failure-v1"]},
    {operation: "mountEditorHistoryRoot", fixtureKinds: ["stick-workspace-history-mount-v1"]},
    {operation: "beginMountedOpen", fixtureKinds: ["stick-mounted-open-candidate-v1"]},
    {operation: "completeMountedOpen", fixtureKinds: ["stick-mounted-open-completion-v1"]},
    {operation: "readCheckpoint", fixtureKinds: []},
  ],
  environmentOperations: [
    {operation: "installEnvironmentPlan", fixtureKinds: ["stick-browser-environment-plan-v1"]},
    {operation: "releaseEnvironmentGate", fixtureKinds: ["stick-browser-environment-gate-release-v1"]},
    {operation: "readEnvironmentCheckpoint", fixtureKinds: []},
    {operation: "clearEnvironmentPlan", fixtureKinds: []},
  ],
  pointerTargets: [
    {targetId: "phase-4-stick-canvas", targetKind: "authorized-canvas"},
  ],
  checkpointKinds: ["environment", "workspace"],
} as const;
