import type { Facing } from "../rig.ts";
import { fall, fallAndGetUp, getUp } from "./fall.ts";
import { highFive, type HighFiveParams } from "./highFive.ts";
import { getHit, guardUp, stomp, type GetHitParams, type GuardParams, type StompParams } from "./hit.ts";
import { coverUp, kipUp, stompDown, type CoverUpParams, type KipUpParams, type StompDownParams } from "./grapple.ts";
import { groundPunch, type GroundPunchParams } from "./groundPunch.ts";
import { liftSlam, slammed, type LiftSlamParams, type SlammedParams } from "./liftSlam.ts";
import { barrage, barraged, type BarrageParams, type BarragedParams } from "./barrage.ts";
import { spinThrow, spunThrown, type SpinThrowParams, type SpunThrownParams } from "./spinThrow.ts";
import { jump, type JumpParams } from "./jump.ts";
import { sit, type SitParams } from "./sit.ts";
import { squat, type SquatParams } from "./squat.ts";
import { kick, type KickParams } from "./kick.ts";
import { dashPunch, type DashParams } from "./dash.ts";
import { pickUp, type PickUpParams } from "./pickUp.ts";
import { BASE_MOVES, type MoveEntry } from "./plan.ts";
import { punch, type PunchParams } from "./punch.ts";
import { fireBlast, teleport, waterShield, type FireBlastParams, type TeleportParams, type WaterShieldParams } from "./powers.ts";
import { iceMountain, iceThrow, type IceMountainParams, type IceThrowParams } from "./powerIce.ts";
import { laserEyes, type LaserEyesParams } from "./powerLaser.ts";
import { iceBlast, waterBlast, type ElementBlastParams } from "./elementBlast.ts";
import { escort, ESCORT_ABOUT, tug, TUG_ABOUT, type EscortParams, type TugParams } from "./cuffs.ts";
import { catchBall, throwBall, type CatchParams, type ThrowParams } from "./throwCatch.ts";
import { lookBack, LOOK_BACK_ABOUT, type LookBackParams } from "./turn.ts";
import { wave, type WaveParams } from "./wave.ts";
import { blownAway, BLOWN_AWAY_ABOUT, type BlownAwayParams } from "./blownAway.ts";
import { dashSlash, swordBlock, swordChop, swordDodge, swordSlash, swordSpin, swordStep, swordThrust, swordVictory, type DashSlashParams, type SwordBlockParams, type SwordDodgeParams, type SwordStrikeParams } from "./swordMoves.ts";

// SPEC-0017 Phase 2: the whole moves library, by id. The scene plan (and later the AI director) uses
// these ids; the lessons for the AI are made from these same entries.
export const LIBRARY: Record<string, MoveEntry> = {
  ...BASE_MOVES,
  jump: { title: "Jump", side: true, run: (s, p, set) => jump(s, p as JumpParams, set), about: "Jump: crouch (anticipation, arms back), explosive push (arms swing up), arc (`height` x body height: the lowest foot or knee at the top), land with bent knees, stand. `distance` px forward. After a walk or run it is a RUNNING JUMP (a little higher by default: `height` 0.42) (`speed` filled in by the planner): no stop — the last step sinks, arms back, take off from one foot at speed, knees tuck in the air, both feet land and the knees soak it up; `distance` is then the jump's length from the take-off foot to the landing foot (missing = what the speed gives; a harder push can stretch it a little, nothing shortens it: the body never slows down for a jump). A run straight after it runs on from the landing at speed (run, jump, run, jump... the parkour rhythm). Marks `takeoff`, `top`, `land` (and `runOn` when a run takes over)." },
  squat: { title: "Squat", side: true, run: (s, p, set) => squat(s, p as SquatParams, set), about: "Squat down (`depth` 0..1), hold `hold` seconds, stand back up; arms forward for balance. Mark `bottom`." },
  sit: { title: "Sit down", side: true, run: (s, p, set) => sit(s, p as SitParams, set), about: "Sit down on the floor with control, stay `seconds` (breathing), stand back up. Already sitting (after a low get-up from the back), it just settles. `hurt` (set by the planner after a fall; always in the hurt style): legs stretched out, leans over the knee, holds it with both hands and looks at it, rubbing it; draws the feet in before standing. Marks `seated`, `up`." },
  fall: { title: "Fall and get up", side: true, run: (s, p, set) => fallAndGetUp(s, p as Parameters<typeof fallAndGetUp>[1], set), about: "Fall and get up. Moving (`speed` px/s, filled in by the planner after a walk or run): trips mid-stride, no stop — the caught foot stays, the body pitches over, falls with gravity, face-plants hands first and slides (further when faster). Standing with no `direction` (an accident) the planner first walks it a step or two and it trips mid-step; with a `direction` it falls where it stands (a short loss of balance first). `direction` back = slip, feet shoot forward, lands on the back (never sitting), slides if moving. Stays down `seconds`, then gets up slowly (hurt). Marks `impact`, `down`, `up`." },
  fallDown: { title: "Fall down", side: true, run: (s, p, set) => fall(s, p as Parameters<typeof fall>[1], set), about: "Fall down and stay lying (face down, or on the back for `direction` back). Moving (`speed` px/s, filled in after a walk or run): no stop, trip mid-stride, face plant, slide. With no direction it falls the way it's going; standing with no direction and no cause before it (an accident) the planner first walks it a step or two, then it trips. Follow with `getUp`. Marks `impact`, `down`." },
  getUp: { title: "Get up", side: true, run: (s, p, set) => getUp(s, p as Parameters<typeof getUp>[1], set), about: "Get up slowly (hurt) from lying after `fallDown`: from the belly the elbows slide back under the shoulders (chest up on the forearms), the hands set under the chest (elbows up by the neck, never over the head), push up, one foot forward with a hand on the knee, up; from the back sit up, rock forward over the feet, hand on knee, up. `low` (set by the planner when a sit follows): stops part way — crouching over the feet from the belly, sitting from the back. Mark `up` (flow point)." },
  pickUp: { title: "Pick up", side: true, run: (s, p, set) => pickUp(s, p as PickUpParams, set), about: "Bend down and pick up an `object` lying in front (the engine puts it where the hand reaches), end holding it at the chest (a throw can follow). Marks `grab`, `twoHands`, `up`." },
  punch: { title: "Punch", side: true, run: (s, p, set) => punch(s, p as PunchParams, set), about: "Punch from a fighting stance; the engine picks how from `distance` (px, hip to hip, to the target; the planner fills it from `target` or the nearest figure in front): close = uppercut (knees dip, the fist drops low and back beside the hip, then scoops forward and up to the chin), medium = straight jab/cross (the fist pulls straight back until it almost touches the head, then straight out; the other hand pulls back to the face), far or a big power shot = power (elbow lifts and goes behind the head, other arm points at the target, lean back; then the fist comes forward past the head to the shoulder and goes in a straight line to the target, the arm ending level, the arms switch, the body leans forward, the front foot steps in); a low target (`targetHeight`, x height) = overhand (same wind-up, the fist arcs down onto it). `technique` auto/straight/uppercut/power/overhand, `hand` front/back, `height` head/body. Punches in a row alternate hands and flow guard to guard. Marks `windup`, `hit`, `back`." },
  dashPunch: { title: "Dash punch", side: true, run: (s, p, set) => dashPunch(s, p as DashParams, set), about: "Dash punch at `target` (a character id; default the nearest figure in front) from far away: it runs (with no run right before it the planner runs it up first), and at top speed it bends down low on one foot and pushes off: a DASH, flying low and fast, body leaning far forward, the punching arm straight back and the other arm straight out at the target, legs tucked (in the air under half a second, like a running stride, never floating). The fist folds up behind the head and comes over the shoulder straight at the target, landing the same moment the front foot touches down (aimed at where the target really is then). Then friction: the feet skid a little and it slows to a stop, hands loose at the chest. Faster and lower when angry, smaller when tired or hurt; a robot keeps one speed. Pair the target with getHit (`from`). From 20 pictures a second up it adds one squashed picture before the push and one stretched picture after it. Marks `crouch`, `push`, `air`, `windup`, `land` = `hit`, `stop`." },
  kick: { title: "Kick", side: true, run: (s, p, set) => kick(s, p as KickParams, set), about: "Kick: wind-up the opposite way (kicking leg swings back behind the body, chest leans forward, arms out for balance), fast kick forward (`height` low/mid/high) leaning back, the foot comes down once into the fighting stance (in a scene the next move or the end-of-fight stance starts from there). Mark `hit`." },
  wave: { title: "Wave", run: (s, p, set) => wave(s, p as WaveParams, set), about: "Wave hello `times` times (`hand` left/right; default: in a side view the hand nearer the viewer, so the wave is seen); works facing the viewer or to the side. `to` = who it waves to (a character id; default: the nearest figure in front): it looks at them (head up or down) and waves up toward someone high, down toward someone low; someone behind it, it turns to them first. Started with that arm already up (straight after a high-five) it skips the dip and the rise and waves from there. Marks `up`, `down`." },
  lookBack: { title: "Look back", run: (s, p, set) => lookBack(s, p as LookBackParams, set), about: LOOK_BACK_ABOUT },
  highFive: { title: "High-five", side: true, run: (s, p, set) => highFive(s, p as HighFiveParams, set), about: "High-five a partner `partnerDistance` px away (hip to hip, up to ~1.08 x height): step in, arm winds up over and behind the head (leaning back), fast swing until the hands meet tip to tip at the midpoint (hand = end of the forearm; marks `touch` = first contact, `slap` = middle of a brief press; optional `thickness` = line width so the round line ends just touch), step back. At walking pace: winding up takes about one walking step of the same mood; happy = fast slap, angry = stamps the lead foot down, deeper wind-up, really hard and fast slap. Eyes on the partner, on the hands at the slap (`with` = the partner's id; default the nearest figure in front). Both figures face each other; sync one figure's `slap` to the other's. Moods: robot = straight stiff arm up the front, round behind the head, slap, back round, down the way it went (even speeds); mad = hunched, free arm out bent behind, harder slap; happy = chest up, free arm flung back, big bounce. With another move straight after, the arm hands over still up or back down at the chest, whichever never swings it round in a circle (the planner picks)." },
  throw: { title: "Throw", side: true, run: (s, p, set) => throwBall(s, p as ThrowParams, set), about: "Throw a held object to `to` (a character id) or `distance` px (hip to hip). The engine picks how from the distance by rules: so close they can meet half way (arms out, at most one small step: about 0.9 body heights apart or less) = a HAND-OFF (hold it out with both hands, the other takes it, no flight; `handOff: false` forces a throw); short = underhand toss (ball swings down and back past the hip, knees dip, released at belly height rising); long (past about 2.8 body heights for a 300 px figure: the speed the ball needs vs. a comfortable underhand swing) = OVERHAND: the ball comes up in front of the face, the elbow goes up and back behind the head with the ball above and behind it (held a moment), other arm pointing at the target, lean back; then the elbow leads over, the forearm snaps through, release above the head. `overhand: true/false` forces the kind. `bounce: true` = bounce pass (down to the floor once, up into the catcher's hands; the catch is timed to it). `to: \"away\"` = throw it away: a big overhand, the ball arcs high over anyone in front and off the page, gone. Marks `oneHand`, `windup`, `cocked` (overhand), `release` (hand-off: `offer`, `release` = the other has it); then follow-through, arms down, step back, stand. A robot throws stiff: straight arm behind, round the head and out at even speeds, then back round. Params: `object`, `to`, `overhand`, `bounce`, `handOff`." },
  catch: { title: "Catch", side: true, run: (s, p, set) => catchBall(s, p as CatchParams, set), about: "Catch an object thrown by `from`: from standing, the hands come up in front of the chest, ready (mark `ready`: a reaction time plus raising the hands), then the arms go out to meet the ball (mark `catch`, timed automatically to the ball's arrival — through the air, or off the floor for a bounce pass), it comes in to the chest with a small knee give (mark `secured`), held at the chest. If the giver is close enough for a hand-off, the planner makes it a take instead: hands up, reach out (one small step if needed) and take it from the giver's hands half way (mark `catch` = the moment it changes hands). While waiting the figure rests in its standing pose. Params: `object`, `from`." },
  getHit: { title: "Get hit", side: true, run: (s, p, set) => getHit(s, p as GetHitParams, set), about: "React to a hit from `from` (a character id): the planner times it to that figure's next punch or kick landing and measures how hard it was (STRIKE POWER: how far the fist or foot travelled from its wind-up, how long the wind-up took, the attacker's energy and style). `result` (optional) says what happens: \"block\" (the guard stops it), \"hit\" (it lands; the engine picks the reaction), \"stagger\", \"catch\" (almost falls, catches itself), \"knockdown\" or \"grab\" (catches the fist in both hands, the punch stops in them; counts as blocked). Not given, the engine picks by power: small = flinch (head snaps back, guard straight back); medium = stagger (snap, the back foot steps back to catch the weight, twice for a harder hit); bigger = almost falls and catches itself; big = knocked down (falls on its back, stays down, gets up slowly) — only if the page has room behind it to fall, otherwise it almost falls instead. Each hit adds damage (power to the fourth; a blocked one almost none): a hurt figure is knocked about more easily, stays down longer, recovers slower and stands more and more slumped; when fully beaten a knock-down is the end (mark `out`). Knocked off its spot, it steps back to it once its guard is back. Marks `hit`, `react`, `ready` (guard back up, on its spot), `block`, `grab`, `teeter`, `caught`, `down`, `up`, `out`." },
  block: { title: "Block", side: true, run: (s, p, set) => getHit(s, { ...(p as GetHitParams), result: "block" }, set), about: "Block a punch from `from` (= getHit with result \"block\"; counts as a hit taken, timed to their next strike): the forearms come up in front of the face just before the punch lands, the chin tucks behind them; the blow pushes the body back a little over its planted feet (the head barely moves); then the guard comes back. Almost no damage. Marks `hit`, `block`, `ready`." },
  almostFall: { title: "Almost fall, catch yourself", side: true, run: (s, p, set) => getHit(s, { ...(p as GetHitParams), result: "catch" }, set), about: "A big hit from `from` almost knocks it over (= getHit with result \"catch\"): the head snaps back first, then the chest goes back and the back foot steps back to catch the weight, the arms flying up last; it teeters THROWN OFF BALANCE (head and chest back past the hips, one arm up over the head (elbow up in front of the face, forearm over the top of the head; the hand goes the short straight way past the face, the elbow never flips), the other elbow flung back at shoulder height, standing on the bent back leg, the front leg straight out with its foot up); then the front foot steps back down under it, the weight comes forward and the arms come down the way they went up into the guard. No arm changes its mind on the way. No fall. Marks `hit`, `react`, `teeter`, `caught`, `ready`." },
  guard: { title: "Guard", side: true, run: (s, p, set) => guardUp(s, p as GuardParams, set), about: "Stand in the fighting stance with the hands up (slumped as the figure gets hurt), breathing, for `seconds`. Sync its `start` to the other fighter's `ready` to wait for them to get back up before attacking again." },
  stomp: { title: "Stomp", side: true, run: (s, p, set) => stomp(s, p as StompParams, set), about: "A stomp is a strike with the foot, straight down on a spot just in front: eyes on the spot; the knee comes up HIGH while the body rises tall on the standing leg, leaning IN (never back), fists tight at the chest; a moment at the top; then the foot SLAMS down fast, fists driven down by the hips, the chest pitching in; a small jolt and recoil on impact (knees give only a little, both feet stay down: no hop, no limp); then up again. Repeated stomps land on the same spot with the same beat. Moods: angry/irritated hardest and hunched; happy a stamp of joy (chest up, fists pumped); robot stiff (straight arms, even speed, no give); tired/sad/hurt small and weak. The standing foot never moves. `size` 0.5..1.3. Marks `windup`, `stomp`." },
  // GROUND FIGHTING (grapple.ts, round 9): two-figure moves for when one fighter is down.
  stompDown: { title: "Stomp on someone down", side: true, run: (s, p, set) => stompDown(s, p as StompDownParams, set), about: "Stomp on a figure lying on the floor (`target`: its id; default the nearest one lying in front). The planner walks it to where the body lies first (or steps back, or turns), then: weight onto the back foot, the knee comes up HIGH over the body (chest rising, leaning back a little, arms rising: anticipation up for a strike down), hangs a moment, the foot drives straight down ONTO the belly (it really touches the body, worked out from how it lies), hips dropping, chest over it, arms whipping down; pressed in a moment, then the foot comes off and steps back beside the other. Looks at the spot all the way. `size` 0.5..1.3. Marks `windup`, `stomp` (also \"<id>.groundHit<k>\"). Pair it with `coverUp` (`from`) on the one lying down." },
  liftSlam: { title: "Lift and slam someone down", side: true, run: (s, p, set) => liftSlam(s, p as LiftSlamParams, set), about: "A ground attack on a figure lying on its back (`target`: its id; default the nearest one lying in front). The planner walks it to the body first, then: it bends right down over the waist (a deep squat, back forward), both hands grab the waist, it straightens up LIFTING the body off the floor (held up in front of the chest, hanging upright and limp, legs dangling), lifts it a little higher leaning back (the wind-up), then SLAMS it down hard onto its back on the floor in front of him, follows through bent over, lets go and stands. `size` 0.5..1.3. Marks `grab`, `lift`, `windup`, `slam` = `stomp` (also \"<id>.groundHit<k>\"), `release`, `up`. Pair it with `slammed` (`from`) on the one lying down (not coverUp)." },
  slammed: { title: "Get lifted and slammed", side: true, run: (s, p, set) => slammed(s, p as SlammedParams, set), about: "Lying on its back under a liftSlam from `from` (a character id; timed automatically to that figure's lift and slam): sees it coming (head up), is grabbed by the waist, lifted up (its hips stay in the lifter's hands every moment, hanging limp and upright, legs dangling, never into the floor), slammed down flat on its back, jolts with the impact (legs up, shoulders curl, slams back flat), lies there hurt, then lies back as it lay. Ends lying (follow with getUp or kipUp). Marks `sees`, `grab`, `lift`, `hit` = `slam`, `down`." },
  spinThrow: { title: "Grab, spin and throw", side: true, run: (s, p, set) => spinThrow(s, p as SpinThrowParams, set), about: "A special attack on a STANDING figure close in front (`target`: its id; within about a fighting step): steps in, bends a little and grabs the waist with both hands, pulls the body up off its feet and SPINS on the spot, almost two turns, getting faster (seen from the side it turns to face wherever the held one is: the held one swings round from its front to its back and round again, flung out at the sides, tucked small passing in front or behind), then LETS GO just before the held one swings out in front, so it flies off forward; follows through and settles back into its stance. Marks `grab`, `spin`, `release`, `ready`. Pair it with `spunThrown` (`from`) on the one thrown." },
  spunThrown: { title: "Get spun and thrown", side: true, run: (s, p, set) => spunThrown(s, p as SpunThrownParams, set), about: "Standing, grabbed by a spinThrow from `from` (a character id; timed automatically to that figure's grab and release): grabbed by the waist, pulled off its feet and swung round (its hips stay in the thrower's hands every moment, never into the floor), let go, flies off away from the thrower through the air (a short arc, `distance` x height, default 1.5), lands on its back, slides and jolts, and lies there. Ends lying (follow with kipUp or getUp). Marks `grab`, `spin`, `release`, `land`, `down`, `ready`." },
  barrage: { title: "Punch barrage", side: true, run: (s, p, set) => barrage(s, p as BarrageParams, set), about: "A fast BARRAGE of `count` (6..10, default 8) punches at a STANDING figure in front (`target`: its id): first into a punching stance where its straights reach with the arm straight (a small step in, or back if too close), a short anticipation, then punch after punch on ONE STEADY BEAT (about every 0.2 s; the next fist goes out as the last comes back), hands alternating left/right (sometimes the same hand twice). Every punch has a small load inside the beat (a little lean back, then the punch). Mostly straights (level, the arm straight at contact, straight back), mixed with overhands (from up by the temple over and down onto the guard), uppercuts (from low up into the bottom of the guard) and about three strong ones (a bigger lean back) — a different mix for each `seed`. Only a very long barrage (15 s and more) slows a little. Every blocked punch lands on the other's covering forearms. The last punch loads low (mark `cock`), steps in and drives into the stomach under the guard, then comes straight back out low (never near the other's head). Marks `windup`, `hit1`..`hitN` (each fist landing), `cock`, `hit` (= the last), `ready` = `end` (back in its stand, facing the other). Pair it with `barraged` (`from`) on the one punched." },
  barraged: { title: "Take a punch barrage", side: true, run: (s, p, set) => barraged(s, p as BarragedParams, set), about: "Standing, under a barrage from `from` (a character id; timed automatically to that figure's punches: the planner hands it when each one lands): covers up (forearms up in front of the face, chin tucked), every punch lands on the forearms with a small knock-back jolt (head and chest giving a little), driven back one step half way through (the back foot after one punch, the front foot after the next), and the LAST punch gets in under the guard to the stomach: it doubles over at the stomach (hips back, knees giving, hands to the belly), then straightens back up. Marks `covered`, `hit1`..`hitN`, `hit` (= the last), `react`, `ready`." },
  groundPunch: { title: "Hop and punch someone down", side: true, run: (s, p, set) => groundPunch(s, p as GroundPunchParams, set), about: "A ground attack like stompDown, with the fist: on a figure lying on the floor (`target`: its id; default the nearest one lying in front). The planner brings it to a hop away from the body, then: down over the push foot (arms swung back), a HOP up into the air, the punching arm coming forward and UP until the fist is cocked high over the head, the other arm reaching at the body; gravity pulls it down and the fist drives down ONTO the chest/belly (worked out from how it lies) as it lands, front foot down, back knee on the floor, chest over the body; pressed in a moment, then it stands back up beside the body. Looks at the spot all the way. `size` 0.5..1.3. Marks `hop`, `top`, `stomp` (the fist lands; also \"<id>.groundHit<k>\"). Pair it with `coverUp` (`from`) on the one lying down." },
  coverUp: { title: "Cover up on the ground", side: true, run: (s, p, set) => coverUp(s, p as CoverUpParams, set), about: "Lying on its back under a ground attack from `from` (a character id; timed automatically to that figure's next ground attack landing, e.g. a stompDown): sees it coming (head up, chin down), covers just before it lands (knees pulled up to the chest, forearms crossed over the chest and face), is DRIVEN FLAT the moment it lands (back and head slam down, arms crushed onto the chest, legs jolt up), curls up holding its belly, then lies back down. Ends lying where it lay (follow with getUp). Marks `sees`, `covered`, `hit`, `down`." },
  kipUp: { title: "Kip-up (quick get-up)", side: true, run: (s, p, set) => kipUp(s, p as KipUpParams, set), about: "Get up FAST from lying on the back (a fighter who isn't beaten, after `coverUp` or any fall onto the back): rocks back onto the shoulders (knees tucked over the chest, hands by the ears: the anticipation), then whips the legs forward and down, the hips fly up and the body rolls up over them, lands crouched on both feet a little further back and rises straight into the fighting guard (a punch or kick can follow). Lying face down it does the ordinary get-up. Marks `rock`, `kip`, `land`, `up`." },
  // POWERS (powers.ts, Phase 2C): a body move plus an effect, timed by the move's marks.
  fireBlast: { title: "Fire blast", side: true, run: (s, p, set) => fireBlast(s, p as FireBlastParams, set), about: "Shoot fire from both palms at `target` (a character id) or `distance` px ahead: ANTICIPATION first (both hands pulled back to the hip, lean back, knees bend), then THRUST both palms forward, stepping in (front foot forward, a lunge); the fire pours out for `seconds` (default 0.8) while he holds the push; the force pushes him back a little (recoil) and he braces into it; then the arms come down and he steps back and stands. Effects: a fire stream from the front hand from `release` to `end` (`color`/`color2` = the fire's colors), a fire burst where it lands; a target holding a water shield is hit on the shield's edge (steam where they meet) and holds. Marks `windup`, `release`, `recoil`, `end`." },
  waterShield: { title: "Water shield", side: true, run: (s, p, set) => waterShield(s, p as WaterShieldParams, set), about: "Raise a water shield for `seconds` (default 1.5): crouch a little with the forearms crossed low (anticipation), then the arms sweep up and spread and the knees brace — the shield (a water bubble in front of the chest) is up from `hold` to `release`; then the arms lower and he stands. A fire blast aimed at him (sync `hold` a little before its `release`) hits the shield: he is pushed back a little and braces again (mark `pushed`) but holds — never knocked over. `color`/`color2` = the water's colors. Marks `raise`, `hold`, `release`." },
  teleport: { title: "Teleport", side: true, run: (s, p, set) => teleport(s, p as TeleportParams, set), about: "Teleport to stage x `to` (or `distance` px forward, back if negative) — QUICK: crouch (anticipation), a quick flash at the start spot and the body is gone in one instant (a marked fast span), then APPEAR at the new spot in another quick flash, crouched, and he stands up. Never a dust cloud. NO TURN first: it goes anywhere, in front or behind, and he keeps facing the way he faced. Marks `crouch`, `vanish`, `appear`, `end` (and `fastFrom`/`fastTo`)." },
  // ICE (powerIce.ts, Phase 2C).
  iceMountain: { title: "Ice mountain", side: true, run: (s, p, set) => iceMountain(s, p as IceMountainParams, set), about: "Lift a hand and an ICE MOUNTAIN grows out of the ground: anticipation (a small crouch, the casting hand pulled down and back by the hip), then the hand LIFTS UP in front and from `release` jagged ice spikes burst up, small to big, running along the ground to `target` (a character id; the biggest comes up where it stands at `reach` — sync a jump back to it) or `distance` px ahead; with neither (or `shape: \"mountain\"`) one big mountain. The hand stays up while the ice stands `seconds` (1); lowering it cracks the ice (`end`) and it SHATTERS into Ice crystal pieces in frost mist (`shatter`). `color`/`color2` = ice / dark edge. Marks `windup`, `release`, `lift`, `reach`, `end`, `shatter`." },
  iceThrow: { title: "Throw ice crystals", side: true, run: (s, p, set) => iceThrow(s, p as IceThrowParams, set), about: "Throw `count` (3) ice crystals at `target` (a character id) or `distance` px ahead (onto the ground): anticipation (weight back, the throwing hand drawn back behind the hip, the front hand aiming), then the front foot steps in and the hand whips through, releasing the crystals in front of the chest (`release`), follow-through, step back. The crystals (Ice crystal symbols) spin and SHATTER on the hit (`hit`: the first one). A target holding a water shield (sync its `hold` a little before `release`) is hit on the shield's edge, pushed back a little, and holds. `color`/`color2` = ice / dark edge. Marks `windup`, `release`, `hit`, `end`." },
  // LASER EYES (powerLaser.ts, Phase 2C extras).
  laserEyes: { title: "Laser eyes", side: true, run: (s, p, set) => laserEyes(s, p as LaserEyesParams, set), about: "Two thin laser beams from the eyes at `target` (a character id: its chest; `at: \"ground\"` = the ground in front of it) or the ground `distance` px ahead. ANTICIPATION: the head dips, fists back, knees soften, the EYES GLOW; then the head snaps up and the beams shoot (`color` = glow, default red; `color2` = core); a small RECOIL (head back, slight lean back, knees soften); he holds for `seconds` (default 1; `sweep` px slides the hit along the ground), the beams cut off, the eyes fade. Where they hit: sparks, a scorch that cools, a little smoke, a thin light on the ground. Marks `charge`, `release`, `hit` (sync a jump back to it), `recoil`, `end`." },
  // ELEMENT BLASTS (elementBlast.ts, Phase 2C extras: ELEMENTAL FIGHTS; what they do when they meet another power: elements.ts).
  iceBlast: { title: "Ice blast", side: true, run: (s, p, set) => iceBlast(s, p as ElementBlastParams, set), about: "Shoot a STREAM OF ICE from both palms at `target` (a character id) or `distance` px ahead — the fire blast's body (hands pulled back to the hip, step in and thrust both palms, recoil and brace while it pours for `seconds`, arms down): a cone of frost with crystals flying in it; where it hits, ice shards and frost. Fired at someone who fires a beam back at the same time, the two CLASH in the middle (`win: true` = this side's push wins). Marks `windup`, `release`, `recoil`, `end`." },
  waterBlast: { title: "Water blast", side: true, run: (s, p, set) => waterBlast(s, p as ElementBlastParams, set), about: "Shoot a JET OF WATER from both palms at `target` (a character id) or `distance` px ahead — the fire blast's body; a splash where it hits; fire meeting it makes steam; fired at someone who fires back at the same time, the two CLASH in the middle (`win: true` = this side wins). Marks `windup`, `release`, `recoil`, `end`." },
  // HANDCUFFS AND A POLICE ESCORT (cuffs.ts, Phase 2C extras): a cuffed figure is a character option (`cuffed: true`).
  escort: { title: "Escort (police)", side: true, run: (s, p, set) => escort(s, p as EscortParams, set), about: ESCORT_ABOUT },
  tug: { title: "Tug free (cuffed)", side: true, run: (s, p, set) => tug(s, p as TugParams, set), about: TUG_ABOUT },
  // (Phase 2C: thrown by an explosion — blownAway.ts.)
  blownAway: { title: "Blown away by a blast", side: true, run: (s, p, set) => blownAway(s, p as BlownAwayParams, set), about: BLOWN_AWAY_ABOUT },
  // WEAPON MOVES (swordMoves.ts, Phase 2C extras: WEAPON FIGHTS). The weapon (`weapon`: moves/weapons.ts) is a symbol held
  // along the forearm (a "heldWeapon" effect track); `hand` = the holding hand. Timed by the director (weaponFight.ts).
  swordSlash: { title: "Weapon slash", side: true, lessonMarks: ["windup", "hit", "ready"], run: (s, p, set) => swordSlash(s, p as SwordStrikeParams, set), about: "Slash: `side` down (high behind, down across) / up (low behind, rising) — alternated, an X. Wind-up, step in `lunge` (x height) as it swings into \"hit\", hit stop, follow-through (rebound if `blocked`/`parried`), steps back. `advance`: steps in/out first; `strong`: long coil, very fast swing." },
  swordChop: { title: "Overhead chop", side: true, lessonMarks: ["windup", "hit"], run: (s, p, set) => swordChop(s, p as SwordStrikeParams, set), about: "Strong: two hands coil it high behind the head, then straight down very fast (\"hit\"); as swordSlash." },
  swordThrust: { title: "Weapon thrust", side: true, lessonMarks: ["windup", "hit"], run: (s, p, set) => swordThrust(s, p as SwordStrikeParams, set), about: "Strong: pulled back by the hip, then a lunge straight out at the chest (\"hit\"); as swordSlash." },
  swordSpin: { title: "Spin attack", side: true, lessonMarks: ["windup", "hit"], run: (s, p, set) => swordSpin(s, p as SwordStrikeParams, set), about: "Strong: coil, hop and full turn, landing into a level slash (\"hit\"); as swordSlash." },
  dashSlash: { title: "Dash slash", side: true, lessonMarks: ["push", "hit"], run: (s, p, set) => dashSlash(s, p as DashSlashParams, set), about: "The dash punch with a weapon at `target`: both hands cock it back in the air; slash as the feet land (\"hit\")." },
  swordBlock: { title: "Weapon block", side: true, lessonMarks: ["hit", "ready"], run: (s, p, set) => swordBlock(s, p as SwordBlockParams, set), about: "Block with the weapon on the attacker's \"hit\": `height` mid/high/low; gives ground `push` (x height) by steps; `parry` knocks it aside." },
  swordDodge: { title: "Dodge back", side: true, lessonMarks: ["hit"], run: (s, p, set) => swordDodge(s, p as SwordDodgeParams, set), about: "Hop back `distance` (x height), in the air at \"hit\"." },
  swordStep: { title: "Step in the guard", side: true, lessonMarks: [], run: (s, p, set) => swordStep(s, p as { advance?: number }, set), about: "Real steps in (`advance` x height; out if negative) in the weapon guard." },
  swordVictory: { title: "Weapon raised (victory)", side: true, lessonMarks: ["raised"], run: (s, p, set) => swordVictory(s, p as { seconds?: number }, set), about: "Raise the weapon high and hold it (`seconds`)." },
};

export const facingToward = (fromX: number, toX: number): Facing => (toX >= fromX ? "right" : "left");
